Repository Wai-Technologies/raaghu-angular, pull requests merged in 2022-10, with the labels that each got.

#587 Fixed UI bugs on storybook
  raaghu-elements/src/root/styles-storybook.scss
  raaghu-mfe/projects/cart/src/app/app.component.html
  raaghu-mfe/projects/cart/src/app/cart.stories.ts
  raaghu-mfe/projects/dynamic-property-management/src/app/app.component.html
  raaghu-mfe/projects/dynamic-property-management/src/app/dynamic-property-management.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-address-input/rds-comp-address-input.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-apply-for-position/rds-comp-apply-for-position.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-apply-for-position/rds-comp-apply-for-position.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs-new/rds-comp-audit-logs-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs-new/rds-comp-audit-logs-new.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-pricing-table/rds-comp-pricing-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-product-list/rds-comp-product-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-shopping-cart-product/rds-comp-shopping-cart-product.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-timeline/rds-comp-timeline.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-timeline/rds-comp-timeline.component.scss
Labels: bug

#579 Created Tenant-new page for ABP
  raaghu-mfe/projects/libs/state-management/src/lib/state/tenant-new/tenant-new.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/tenant-new/tenant-new.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/tenant-new/tenant-new.models.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/tenant-new/tenant-new.reducers.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/tenant-new/tenant-new.selectors.ts
  raaghu-mfe/projects/rds-components/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-basic-profile-right/rds-comp-tenant-basic-profile-right.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-basic-profile-right/rds-comp-tenant-basic-profile-right.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-basic-profile-right/rds-comp-tenant-basic-profile-right.component.spec.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-basic-profile-right/rds-comp-tenant-basic-profile-right.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-basic-profile-right/tenant.information.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-features/rds-comp-tenant-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-features/rds-comp-tenant-features.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-features/rds-comp-tenant-features.component.spec.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-features/rds-comp-tenant-features.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-features/tenant.features.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list-new/rds-comp-tenant-list-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list-new/rds-comp-tenant-list-new.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list-new/rds-comp-tenant-list-new.component.spec.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list-new/rds-comp-tenant-list-new.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list-new/tenant.list.new.stories.ts
  raaghu-mfe/projects/rds-components/webpack.config.js
  raaghu-mfe/projects/tenant-new/.browserslistrc
  raaghu-mfe/projects/tenant-new/karma.conf.js
  raaghu-mfe/projects/tenant-new/src/app/app-routing.module.ts
  raaghu-mfe/projects/tenant-new/src/app/app.component.html
  raaghu-mfe/projects/tenant-new/src/app/app.component.scss
  raaghu-mfe/projects/tenant-new/src/app/app.component.spec.ts
  raaghu-mfe/projects/tenant-new/src/app/app.component.ts
  raaghu-mfe/projects/tenant-new/src/app/app.module.ts
  raaghu-mfe/projects/tenant-new/src/app/tenant-new.stories.ts
  raaghu-mfe/projects/tenant-new/src/assets/.gitkeep
  raaghu-mfe/projects/tenant-new/src/bootstrap.ts
  raaghu-mfe/projects/tenant-new/src/environments/environment.prod.ts
  raaghu-mfe/projects/tenant-new/src/environments/environment.ts
  raaghu-mfe/projects/tenant-new/src/favicon.ico
  raaghu-mfe/projects/tenant-new/src/index.html
  raaghu-mfe/projects/tenant-new/src/main.ts
  raaghu-mfe/projects/tenant-new/src/polyfills.ts
  raaghu-mfe/projects/tenant-new/src/styles.scss
  raaghu-mfe/projects/tenant-new/src/test.ts
  raaghu-mfe/projects/tenant-new/tsconfig.app.json
  raaghu-mfe/projects/tenant-new/tsconfig.spec.json
  raaghu-mfe/projects/tenant-new/webpack.config.js
  raaghu-mfe/projects/tenant-new/webpack.prod.config.js
Labels: enhancement

#602 md file changes
  raaghu-elements/src/rds-list-group/src/lib/list-group.md
  raaghu-elements/src/rds-nav-bar/src/lib/nav-bar.md
  raaghu-elements/src/rds-pagination/src/lib/pagination.md
  raaghu-elements/src/rds-popover/src/lib/popover.md
  raaghu-elements/src/rds-search-input/src/lib/search-input.md
  raaghu-elements/src/rds-tags/src/lib/tags.md
  raaghu-mfe/gatsby/static/images/skel-list_group.png
  raaghu-mfe/gatsby/static/images/skel-navbar.png
  raaghu-mfe/gatsby/static/images/skel-pagination.png
  raaghu-mfe/gatsby/static/images/skel-popover.png
  raaghu-mfe/gatsby/static/images/skel-search.png
  raaghu-mfe/gatsby/static/images/skel-tags.png
Labels: bug, gatsby

#603 Development
  raaghu-elements/src/rds-alert/src/lib/alert.md
  raaghu-elements/src/rds-app-details/src/lib/app-details.md
  raaghu-elements/src/rds-avatar/src/lib/avatar.md
  raaghu-elements/src/rds-badge/src/lib/badge.md
  raaghu-elements/src/rds-benefit/src/lib/benefit.md
  raaghu-elements/src/rds-big-number-widget/src/lib/big-number-widget.md
  raaghu-elements/src/rds-breadcrumb/src/lib/breadcrumb.md
  raaghu-elements/src/rds-button/src/lib/button.md
  raaghu-elements/src/rds-card-detail/src/lib/card-detail.md
  raaghu-elements/src/rds-card/src/lib/card.md
  raaghu-elements/src/rds-carousel/src/lib/carousel.md
  raaghu-elements/src/rds-checkbox-groups/src/lib/checkbox-groups.md
  raaghu-elements/src/rds-checkbox-parent-child/src/lib/checkbox-parent-child.md
  raaghu-elements/src/rds-checkbox/src/lib/checkbox.md
  raaghu-elements/src/rds-collapse/src/lib/collapse.md
  raaghu-elements/src/rds-color-picker/src/lib/color-picker.md
  raaghu-elements/src/rds-color/src/lib/color.md
  raaghu-elements/src/rds-datepicker/src/lib/datepicker.md
  raaghu-elements/src/rds-double-range/src/lib/double-range.md
  raaghu-elements/src/rds-dropdown/src/lib/dropdown.md
  raaghu-elements/src/rds-fab-menu/src/lib/fab-menu.md
  raaghu-elements/src/rds-feed/src/lib/feed.md
  raaghu-elements/src/rds-file-uploader/src/lib/file-uploader.md
  raaghu-elements/src/rds-icon-label/src/lib/icon-label.md
  raaghu-elements/src/rds-input/src/lib/input.md
  raaghu-elements/src/rds-label/src/lib/label.md
  raaghu-elements/src/rds-list-group/src/lib/list-group.md
  raaghu-mfe/gatsby/static/images/alert-skeleton.png
  raaghu-mfe/gatsby/static/images/avatar-skeleton.png
  raaghu-mfe/gatsby/static/images/breadcrumb-skeleton.png
  raaghu-mfe/gatsby/static/images/button-skeleton.png
  raaghu-mfe/gatsby/static/images/button-with-label.png
  raaghu-mfe/gatsby/static/images/card-details.png
  raaghu-mfe/gatsby/static/images/checkbox-skeleton.png
  raaghu-mfe/gatsby/static/images/collapse-skeleton.png
  raaghu-mfe/gatsby/static/images/dropdown-skeleton.png
  raaghu-mfe/gatsby/static/images/fab-menu.png
  raaghu-mfe/gatsby/static/images/file-uploader-skeleton.png
  raaghu-mfe/gatsby/static/images/icon-label-skeleton.png
  raaghu-mfe/gatsby/static/images/input-tooltip.png
  raaghu-mfe/gatsby/static/images/label-skeleton.png
  raaghu-mfe/gatsby/static/images/list-group-skeleton.png
Labels: bug, gatsby

#604 Fixed UI bugs on storybook
  raaghu-elements/src/rds-avatar/src/lib/rds-avatar.component.ts
  raaghu-elements/src/rds-card/src/lib/card.stories.ts
  raaghu-mfe/projects/dynamic-property-management/src/app/app.component.html
  raaghu-mfe/projects/dynamic-property-management/src/app/dynamic-property-management.stories.ts
  raaghu-mfe/projects/language/src/app/language.stories.ts
  raaghu-mfe/projects/libs/themes/src/styles/responsive.scss
  raaghu-mfe/projects/maintenance/src/app/maintenance/maintenance.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-edition-new-basic/rds-comp-edition-new-basic.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features-list-new/rds-comp-features-list-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features-list-new/rds-comp-features-list-new.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-invoice/rds-comp-invoice.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-shopping-cart-product/rds-comp-shopping-cart-product.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-shopping-cart-product/rds-comp-shopping-cart-product.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-visual-settings/rds-comp-visual-settings.component.html
  raaghu-mfe/projects/settings/src/app/settings.stories.ts
  raaghu-mfe/projects/under-construction/src/app/app.component.html
  raaghu-mfe/projects/under-construction/src/app/under-construction.stories.ts
  raaghu-mfe/projects/under-maintenance/src/app/app.component.html
  raaghu-mfe/projects/under-maintenance/src/app/under-maintenance.stories.ts
  raaghu-mfe/projects/webhooksubscription/src/app/webhooksubscription.stories.ts
Labels: bug

#606 Development
  raaghu-elements/src/rds-like-dislike/src/lib/like-dislike.md
  raaghu-elements/src/rds-nav-tab/src/lib/nav-tab.md
  raaghu-elements/src/rds-price/src/lib/price.md
  raaghu-elements/src/rds-progressbar/src/lib/progressbar.md
  raaghu-elements/src/rds-radio-button/src/lib/radio-button.md
  raaghu-elements/src/rds-rating/src/lib/rating.md
  raaghu-elements/src/rds-review-category/src/lib/review-category.md
  raaghu-elements/src/rds-scrollspy/src/lib/scrollspy.md
  raaghu-elements/src/rds-search-input/src/lib/search-input.md
  raaghu-elements/src/rds-select-list/src/lib/select-list.md
  raaghu-elements/src/rds-side-nav/src/lib/side-nav.md
  raaghu-elements/src/rds-table/src/lib/table.md
  raaghu-mfe/gatsby/static/images/skel-Radio_button.png
  raaghu-mfe/gatsby/static/images/skel-Rating.png
  raaghu-mfe/gatsby/static/images/skel-Side_nav.png
  raaghu-mfe/gatsby/static/images/skel-Table.png
  raaghu-mfe/gatsby/static/images/skel-like_dislike.png
  raaghu-mfe/gatsby/static/images/skel-price.png
  raaghu-mfe/gatsby/static/images/skel-progress_bar.png
  raaghu-mfe/gatsby/static/images/skel-scrollspy.png
  raaghu-mfe/gatsby/static/images/skel-select_list.png
Labels: bug, gatsby

#607 Enhancement in elements
  raaghu-elements/src/rds-double-range/src/lib/double-range.stories.ts
  raaghu-elements/src/rds-radio-button/src/lib/radio-button.stories.ts
  raaghu-elements/src/rds-radio-button/src/lib/rds-radio-button.component.html
  raaghu-elements/src/rds-radio-button/src/lib/rds-radio-button.component.ts
  raaghu-elements/src/rds-select-list/src/lib/select-list.stories.ts
  raaghu-elements/src/rds-textarea/src/lib/textarea.stories.ts
  raaghu-elements/src/rds-website-metric/src/lib/rds-website-metric.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-basic-profile-right/rds-comp-tenant-basic-profile-right.component.html
Labels: enhancement

#608 Development
  raaghu-elements/src/rds-accordion/src/lib/accordion.md
  raaghu-elements/src/rds-chart-bar-horizontal/src/lib/chart-bar-horizontal.md
  raaghu-elements/src/rds-chart-bar-horizontal/src/lib/chart-bar.md
  raaghu-elements/src/rds-chart-bool/src/lib/chart-bool.md
  raaghu-elements/src/rds-chart-bubble/src/lib/chart-bubble.md
  raaghu-elements/src/rds-chart-doughnut/src/lib/chart-doughnut.md
  raaghu-elements/src/rds-chart-mixed/src/lib/chart-mixed.md
  raaghu-elements/src/rds-chart-pie/src/lib/chart-pie.md
  raaghu-elements/src/rds-chart-polar-area/src/lib/chart-polar-area.md
  raaghu-elements/src/rds-chart-radar/src/lib/chart-radar.md
  raaghu-elements/src/rds-chart-scatter/src/lib/chart-scatter.md
  raaghu-elements/src/rds-chart-stacked/src/lib/chart-stacked.md
  raaghu-mfe/gatsby/static/images/bar-chart-with-border-radius.png
  raaghu-mfe/gatsby/static/images/bar-horizontal-chart.png
  raaghu-mfe/gatsby/static/images/bar-stacked-chart.png
  raaghu-mfe/gatsby/static/images/bar-vertical-chart.png
  raaghu-mfe/gatsby/static/images/mixed-chart1.png
  raaghu-mfe/gatsby/static/images/pie-chart1.png
  raaghu-mfe/gatsby/static/images/pie-multiple.png
  raaghu-mfe/gatsby/static/images/polar-area-chart1.png
Labels: bug, gatsby

#610 committed for element changes
  raaghu-elements/src/rds-address-detail/src/lib/address-detail.stories.ts
  raaghu-elements/src/rds-address-detail/src/lib/rds-address-detail.component.html
  raaghu-elements/src/rds-address-detail/src/lib/rds-address-detail.module.ts
  raaghu-elements/src/rds-app-details/src/lib/app-details.stories.ts
  raaghu-elements/src/rds-app-details/src/lib/rds-app-details.component.html
  raaghu-elements/src/rds-banner/src/lib/banner.stories.ts
  raaghu-elements/src/rds-banner/src/lib/rds-banner.component.html
  raaghu-elements/src/rds-banner/src/lib/rds-banner.component.ts
  raaghu-elements/src/rds-banner/src/lib/rds-banner.module.ts
  raaghu-elements/src/rds-benefit/src/lib/benefit.stories.ts
  raaghu-elements/src/rds-benefit/src/lib/rds-benefit.component.html
  raaghu-elements/src/rds-button-group/src/lib/button-group.stories.ts
  raaghu-elements/src/rds-button-group/src/lib/rds-button-group.component.ts
  raaghu-elements/src/rds-card-detail/src/lib/carddetail.stories.ts
  raaghu-elements/src/rds-card-detail/src/lib/rds-card-detail.component.html
  raaghu-elements/src/rds-color/src/lib/color.stories.ts
  raaghu-elements/src/rds-color/src/lib/rds-color.component.html
  raaghu-elements/src/rds-color/src/lib/rds-color.component.scss
  raaghu-elements/src/rds-color/src/lib/rds-color.component.ts
  raaghu-elements/src/rds-team-member/src/lib/rds-team-member.component.html
Labels: enhancement

#611 Fixed UI bugs on storybook
  raaghu-elements/src/rds-card/src/lib/rds-card.component.scss
  raaghu-elements/src/rds-collapse/src/lib/rds-collapse.component.html
  raaghu-elements/src/rds-color-picker/src/lib/rds-color-picker.component.html
  raaghu-elements/src/rds-color-picker/src/lib/rds-color-picker.component.ts
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.html
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.scss
  raaghu-elements/src/rds-modal/src/lib/modal.stories.ts
  raaghu-elements/src/rds-modal/src/lib/rds-modal.component.html
  raaghu-elements/src/rds-nav-bar/src/lib/rds-nav-bar.component.scss
  raaghu-elements/src/rds-popular-pages/src/lib/rds-popular-pages.component.html
  raaghu-elements/src/rds-popular-pages/src/lib/rds-popular-pages.component.scss
  raaghu-elements/src/rds-product-image/src/lib/rds-product-image.component.html
  raaghu-elements/src/rds-scrollspy/src/lib/rds-scrollspy.component.html
  raaghu-elements/src/rds-scrollspy/src/lib/scrollspy.stories.ts
  raaghu-elements/src/rds-website-metric/src/lib/rds-website-metric.component.html
  raaghu-elements/src/rds-website-metric/src/lib/rds-website-metric.component.ts
  raaghu-elements/src/root/styles-storybook.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/libs/themes/src/styles/responsive.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-order-details/rds-comp-order-details.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-order-details/rds-comp-order-details.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basic-profile-right/rds-comp-user-basic-profile-right.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basics/rds-comp-user-basics.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-website-log/rds-comp-website-log.component.html
Labels: bug

#613 committed for components changes
  raaghu-elements/src/rds-card-detail/src/lib/rds-card-detail.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-contact-information/rds-comp-contact-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-contact-information/rds-comp-contact-information.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-contact-us/rds-comp-contact-us.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-customer-reviews/rds-comp-customer-reviews.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-customer-reviews/rds-comp-customer-reviews.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-identity-management-new/rds-comp-identity-management-new.component.ts
Labels: enhancement

#614 Development
  raaghu-elements/src/rds-fab-menu/src/lib/fabmenu.stories.ts
  raaghu-elements/src/rds-fab-menu/src/lib/rds-fab-menu.component.html
  raaghu-elements/src/rds-fab-menu/src/lib/rds-fab-menu.component.ts
  raaghu-elements/src/rds-feed/src/lib/feed.stories.ts
  raaghu-elements/src/rds-feed/src/lib/rds-feed.component.html
  raaghu-elements/src/rds-icon-label/src/lib/rds-icon-label.component.ts
  raaghu-elements/src/rds-input-group/src/lib/input-group.stories.ts
  raaghu-elements/src/rds-input-group/src/lib/rds-input-group.component.html
  raaghu-elements/src/rds-input-group/src/lib/rds-input-group.component.ts
  raaghu-elements/src/rds-like-dislike/src/lib/rds-like-dislike.component.html
  raaghu-elements/src/rds-nav-bar/src/lib/rds-nav-bar.component.html
  raaghu-elements/src/rds-popover/src/lib/rds-popover.component.html
  raaghu-elements/src/rds-popover/src/lib/rds-popover.component.ts
  raaghu-elements/src/rds-price/src/lib/price.stories.ts
  raaghu-elements/src/rds-price/src/lib/rds-price.component.html
  raaghu-elements/src/rds-price/src/lib/rds-price.component.ts
  raaghu-elements/src/rds-price/src/lib/rds-price.module.ts
  raaghu-elements/src/rds-review-category/src/lib/rds-review-category.component.html
  raaghu-elements/src/rds-review-category/src/lib/review-category.stories.ts
  raaghu-elements/src/rds-widget/src/lib/rds-widget.component.html
  raaghu-elements/src/rds-widget/src/lib/widget.stories.ts
  raaghu-mfe/projects/api-scope/src/app/app.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-billing-address/billingAddress.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-billing-address/rds-comp-billing-address.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-billing-address/rds-comp-billing-address.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-billing/billing.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-billing/rds-comp-billing.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-billing/rds-comp-billing.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-cache/cache.stories.ts
Labels: bug

#615 Fixed UI bugs on storybook
  raaghu-elements/src/rds-pagination/src/lib/rds-pagination.component.html
  raaghu-elements/src/rds-pagination/src/lib/rds-pagination.component.scss
  raaghu-elements/src/rds-stepper/src/lib/rds-stepper.component.html
  raaghu-elements/src/rds-stepper/src/lib/rds-stepper.component.scss
  raaghu-elements/src/rds-stepper/src/lib/rds-stepper.stories.ts
  raaghu-elements/src/rds-website-metric/src/lib/rds-website-metric.component.html
  raaghu-mfe/projects/rds-components/src/app/rdc-comp-api-scope-basics/rdc-comp-api-scope-basics.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-background-image/background-image.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-background-image/rds-comp-background-image.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-background-image/rds-comp-background-image.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-background-image/rds-comp-background-image.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-basic-resource/rds-comp-basic-resource.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-mysettings/rds-comp-mysettings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-mysettings/rds-comp-mysettings.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-properties/properties.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-properties/rds-comp-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basic-profile-right/rds-comp-user-basic-profile-right.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basic-profile-right/rds-comp-user-basic-profile-right.component.scss
Labels: bug

#623 Check specifications of components
  raaghu-elements/.storybook/assets/benefit_type1.svg
  raaghu-elements/.storybook/main.js
  raaghu-elements/src/rds-avatar/src/lib/avatar.stories.ts
  raaghu-elements/src/rds-avatar/src/lib/rds-avatar.component.html
  raaghu-elements/src/rds-avatar/src/lib/rds-avatar.component.ts
  raaghu-elements/src/rds-benefit/src/lib/benefit.stories.ts
  raaghu-elements/src/rds-benefit/src/lib/rds-benefit.component.html
  raaghu-elements/src/rds-button/src/lib/rds-button.component.ts
  raaghu-elements/src/rds-nav-tab/src/lib/rds-nav-tab.component.html
  raaghu-mfe/.storybook/assets/MaskGroup.png
  raaghu-mfe/.storybook/assets/benefit_type1.png
  raaghu-mfe/.storybook/assets/benefit_type2 copy.svg
  raaghu-mfe/.storybook/assets/benefit_type2.svg
  raaghu-mfe/.storybook/assets/benefit_type3.svg
  raaghu-mfe/.storybook/assets/benefit_type4.svg
  raaghu-mfe/projects/host/src/assets/benefit_type1.png
  raaghu-mfe/projects/host/src/assets/benefit_type2.svg
  raaghu-mfe/projects/host/src/assets/benefit_type3.svg
  raaghu-mfe/projects/host/src/assets/benefit_type4.svg
  raaghu-mfe/projects/rds-components/src/app/rds-comp-benefit/benefit.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-benefit/rds-comp-benefit.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-cache/rds-comp-cache.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-linked-accounts/rds-comp-linked-accounts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
Labels: bug

#621 Check specifications of components
  raaghu-mfe/projects/rds-components/src/app/rdc-comp-api-scope-resources/rdc-comp-api-scope-resources.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-address-input/rds-comp-address-input.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-alert-popup/alert-popup.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-alert-popup/rds-comp-alert-popup.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-app-details/app-details-comp.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-apply-for-position/rds-comp-apply-for-position.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/auditlog.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-basic-resource/basic-resource.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-basic-resource/rds-comp-basic-resource.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-basic-resource/rds-comp-basic-resource.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
Labels: bug

#698 committed changes for previous and next and read more functionality
  raaghu-mfe/gatsby/src/assets/data/elements.json
  raaghu-mfe/gatsby/src/pages/{markdownRemark.frontmatter__slug}.js
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/admin-dashboard.md
  raaghu-mfe/projects/rds-components/src/app/rds-comp-basic-resource/basic-resource.md
  raaghu-mfe/projects/rds-components/src/app/rds-comp-billing-address/billing-address.md
  raaghu-mfe/projects/rds-page-api-resources/src/api-resources.md
Labels: bug, gatsby

#676 Fixed UI bugs on storybook
  raaghu-elements/src/rds-alert/src/lib/rds-alert.component.html
  raaghu-elements/src/rds-alert/src/lib/rds-alert.component.scss
  raaghu-elements/src/rds-badge/src/lib/badge.stories.ts
  raaghu-elements/src/rds-badge/src/lib/rds-badge.component.ts
  raaghu-elements/src/rds-benefit/src/lib/rds-benefit.component.html
  raaghu-elements/src/rds-card/src/lib/rds-card.component.scss
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.html
  raaghu-elements/src/rds-like-dislike/src/lib/rds-like-dislike.component.html
  raaghu-elements/src/rds-pagination/src/lib/rds-pagination.component.scss
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.scss
  raaghu-elements/src/rds-website-metric/src/lib/rds-website-metric.component.html
  raaghu-elements/src/root/styles-storybook.scss
  raaghu-mfe/projects/libs/themes/src/styles/responsive.scss
  raaghu-mfe/projects/libs/themes/src/styles/toast.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-account-new/rds-comp-account-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-member-activity/memberactivity.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-member-activity/rds-comp-member-activity.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
Labels: bug

#622 Element, page and component enhancement
  raaghu-elements/src/rds-avatar/src/lib/avatar.stories.ts
  raaghu-elements/src/rds-avatar/src/lib/rds-avatar.component.html
  raaghu-elements/src/rds-icon/src/lib/icons.ts
  raaghu-elements/src/rds-nav-tab/src/lib/rds-nav-tab.component.html
  raaghu-mfe/.storybook/assets/edit-pic-dark-mode.png
  raaghu-mfe/.storybook/assets/edit-pic.png
  raaghu-mfe/.storybook/assets/firefox.png
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-personal-info/rds-comp-personal-info.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-properties/rds-comp-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list-new/tenant.list.new.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/tenantlist.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/top-navigation.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basic-profile-right/rds-comp-user-basic-profile-right.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basics/rds-comp-user-basics.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-delegations/rds-comp-user-delegations.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-table/rds-comp-user-table.component.html
  raaghu-mfe/projects/rds-page-language-text/src/app/language-text.stories.ts
  raaghu-mfe/projects/rds-page-securitylog/src/app/Security-log.stories.ts
  raaghu-mfe/projects/rds-page-settings/src/app/settings.stories.ts
  raaghu-mfe/projects/rds-page-tenant/src/app/tenant.stories.ts
Labels: enhancement

#703 Fixed UI bugs on storybook
  raaghu-elements/src/rds-benefit/src/lib/rds-benefit.component.html
  raaghu-elements/src/rds-big-number-widget/src/lib/big-number-widget.stories.ts
  raaghu-elements/src/rds-big-number-widget/src/lib/rds-big-number.component.html
  raaghu-elements/src/rds-nav-bar/src/lib/rds-nav-bar.component.scss
  raaghu-elements/src/rds-nav-tab/src/lib/rds-nav-tab.component.scss
  raaghu-elements/src/rds-team-member/src/lib/rds-team-member.component.html
  raaghu-elements/src/rds-testimonial/src/lib/rds-testimonial.component.html
  raaghu-elements/src/rds-testimonial/src/lib/rds-testimonial.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login-attempts/rds-comp-login-attempts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-open-position/rds-comp-open-position.component.html
Labels: bug

#710 Storybook>>Functionality>>#680---(rds-widget,textarea,websitemetrics)
  raaghu-elements/src/rds-button/src/lib/rds-button.component.ts
  raaghu-elements/src/rds-chart-line/src/lib/rds-chart-line.component.ts
  raaghu-elements/src/rds-icon/src/lib/rds-icon.component.ts
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.scss
  raaghu-elements/src/rds-textarea/src/lib/rds-textarea.component.html
  raaghu-elements/src/rds-textarea/src/lib/rds-textarea.component.ts
  raaghu-elements/src/rds-textarea/src/lib/textarea.stories.ts
  raaghu-elements/src/rds-website-metric/src/lib/rds-website-metric.component.html
  raaghu-elements/src/rds-website-metric/src/lib/rds-website-metric.component.ts
  raaghu-elements/src/rds-website-metric/src/lib/website-metric.stories.ts
  raaghu-elements/src/rds-widget/src/lib/rds-widget.component.html
  raaghu-elements/src/rds-widget/src/lib/rds-widget.component.ts
  raaghu-elements/src/rds-widget/src/lib/widget.stories.ts
  raaghu-elements/tsconfig.json
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-cache/rds-comp-cache.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-cache/rds-comp-cache.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-website-log/rds-comp-website-log.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-website-log/rds-comp-website-log.component.ts
  raaghu-mfe/projects/rds-page-maintenance/src/app/app.component.ts
  raaghu-mfe/projects/stories/Introduction.stories.mdx
  raaghu-mfe/tsconfig.json
  raaghu-mfe/utils/sync-elements.js
Labels: bug

#709 Enhancement in elements UI & Audit logs Add hand cursor for date fields.(on hovering)
  raaghu-elements/src/rds-double-range/src/lib/double-range.stories.ts
  raaghu-elements/src/rds-pagination/src/lib/rds-pagination.component.html
  raaghu-elements/src/rds-price/src/lib/price.stories.ts
  raaghu-elements/src/rds-price/src/lib/rds-price.component.html
  raaghu-elements/src/rds-price/src/lib/rds-price.module.ts
  raaghu-elements/src/rds-progressbar/src/lib/progressbar.stories.ts
  raaghu-elements/src/rds-progressbar/src/lib/rds-progressbar.component.html
  raaghu-elements/src/rds-range/src/lib/range.stories.ts
  raaghu-elements/src/rds-range/src/lib/rds-range.component.html
  raaghu-elements/src/rds-range/src/lib/rds-range.component.scss
  raaghu-elements/src/rds-range/src/lib/rds-range.component.ts
  raaghu-elements/src/rds-spinner/src/lib/spinners.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
Labels: bug

#715 committed for admin dashboard card issue
  raaghu-elements/src/rds-pagination/src/lib/rds-pagination.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.html
Labels: bug

#718 UI Bug Fixes- #655, #658, #660, #708, #668
  raaghu-elements/.storybook/preview-head.html
  raaghu-elements/src/rds-address-detail/src/lib/rds-address-detail.component.html
  raaghu-elements/src/rds-address-detail/src/lib/rds-address-detail.component.ts
  raaghu-elements/src/rds-address-detail/src/lib/rds-address-detail.module.ts
  raaghu-elements/src/rds-alert/src/lib/alert.stories.ts
  raaghu-elements/src/rds-alert/src/lib/rds-alert.component.html
  raaghu-elements/src/rds-alert/src/lib/rds-alert.component.scss
  raaghu-elements/src/rds-alert/src/lib/rds-alert.component.ts
  raaghu-elements/src/rds-app-details/src/lib/rds-app-details.component.html
  raaghu-elements/src/rds-app-details/src/lib/rds-app-details.component.ts
  raaghu-elements/src/rds-badge/src/lib/badge.stories.ts
  raaghu-elements/src/rds-badge/src/lib/rds-badge.component.scss
  raaghu-elements/src/rds-badge/src/lib/rds-badge.component.ts
  raaghu-elements/src/rds-banner/src/lib/banner.stories.ts
  raaghu-elements/src/rds-banner/src/lib/rds-banner.component.ts
  raaghu-elements/src/rds-benefit/src/lib/rds-benefit.component.html
  raaghu-elements/src/rds-breadcrumb/src/lib/rds-breadcrumb.component.html
  raaghu-elements/src/rds-breadcrumb/src/lib/rds-breadcrumb.component.scss
  raaghu-elements/src/rds-button/src/lib/rds-button.component.html
  raaghu-elements/src/rds-card-detail/src/lib/rds-card-detail.component.html
  raaghu-elements/src/rds-card-detail/src/lib/rds-card-detail.component.ts
  raaghu-elements/src/rds-dropdown/src/lib/rds-dropdown.component.html
  raaghu-elements/src/rds-nav-tab/src/lib/rds-nav-tab.component.html
  raaghu-elements/src/rds-nav-tab/src/lib/rds-nav-tab.component.ts
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.scss
  raaghu-elements/src/root/styles-storybook.scss
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.html
Labels: bug, ASP.net

#721 committed for identity management story issue
  raaghu-mfe/projects/rds-components/src/app/rds-comp-identity-management-new/identity-management.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-identity-management-new/rds-comp-identity-management-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-identity-management-new/rds-comp-identity-management-new.component.ts
Labels: bug

#736 Fixed UI bugs
  raaghu-elements/src/rds-double-range/src/lib/double-range.stories.ts
  raaghu-elements/src/rds-modal/src/lib/rds-modal.component.html
  raaghu-elements/src/rds-progressbar/src/lib/rds-progressbar.component.html
  raaghu-elements/src/rds-range/src/lib/range.stories.ts
  raaghu-elements/src/rds-range/src/lib/rds-range.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-customer-reviews/rds-comp-customer-reviews.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-password-settings/rds-comp-password-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-product-list/rds-comp-product-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-product-overview/rds-comp-product-overview.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-basic-profile-right/rds-comp-tenant-basic-profile-right.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-basic-profile-right/rds-comp-tenant-basic-profile-right.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-features/rds-comp-tenant-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list-new/rds-comp-tenant-list-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list-new/tenant.list.new.stories.ts
Labels: bug

#741 committed changes for adding light-dark theme to storybook
  raaghu-elements/.storybook/main.js
  raaghu-elements/.storybook/manager.js
  raaghu-elements/.storybook/preview.js
  raaghu-elements/package.json
  raaghu-elements/src/rds-address-detail/src/lib/rds-address-detail.module.ts
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.scss
  raaghu-elements/src/root/styles-storybook.scss
Labels: bug, storybook

#739 Development
  raaghu-elements/package.json
  raaghu-mfe/projects/rds-components/src/app/rds-comp-calendar/calender.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-calendar/rds-comp-calendar.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-calendar/rds-comp-calendar.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-identity-management-new/identity-management.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-settings-new/settings-new.stories.ts
Labels: bug, ASP.net

#719 Notification comp enhancement
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-notification/notification.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-notification/rds-comp-notification.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-notification/rds-comp-notification.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-table/rds-comp-user-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-table/rds-comp-user-table.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-table/user-table.stories.ts
  raaghu-mfe/projects/rds-page-audit-logs/src/app/auditlog.stories.ts
Labels: enhancement

#753 Storybook UI bugs specification
  raaghu-elements/src/rds-button/src/lib/rds-button.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-page-not-found/rds-comp-page-not-found.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-page-not-found/rds-comp-page-not-found.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-password-settings/password-settings.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-password-settings/rds-comp-password-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-password-settings/rds-comp-password-settings.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-payment-details/rds-comp-payment-details.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-personal-info/rds-comp-personal-info.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-shipping-address/rds-comp-shipping-address.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-subscription/rds-comp-subscription.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.html
Labels: bug

#783 Checking specifications of components
  raaghu-mfe/projects/rds-components/src/app/rds-comp-claims/claims.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-claims/rds-comp-claims.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-claims/rds-comp-claims.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-resources/rds-comp-client-resources.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-hierarchy/hierarchy.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login-attempts/login-attempts.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login-attempts/rds-comp-login-attempts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login-attempts/rds-comp-login-attempts.component.ts
Labels: enhancement

#785 Development Gatsby>>Responsiveness#768
  raaghu-elements/.storybook/preview-head.html
  raaghu-elements/src/rds-button/src/lib/button.md
  raaghu-elements/src/rds-checkbox-groups/src/lib/checkbox-groups.md
  raaghu-elements/src/rds-checkbox-parent-child/src/lib/checkbox-parent-child.md
  raaghu-elements/src/rds-dropdown/src/lib/dropdown.md
  raaghu-elements/src/rds-fab-menu/src/lib/fab-menu.md
  raaghu-elements/src/rds-feature-list/src/lib/feature-list.md
  raaghu-elements/src/rds-file-uploader/src/lib/file-uploader.md
  raaghu-elements/src/rds-price/src/lib/price.md
  raaghu-elements/src/rds-radio-button/src/lib/radio-button.md
  raaghu-elements/src/rds-range/src/lib/range.md
  raaghu-elements/src/rds-rating/src/lib/rating.md
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.scss
  raaghu-elements/src/rds-size/src/lib/size.md
  raaghu-elements/src/rds-spinner/src/lib/spinner.md
  raaghu-elements/src/rds-table/src/lib/table.md
  raaghu-elements/src/rds-testimonial/src/lib/rds-testimonial.component.html
  raaghu-elements/src/rds-testimonial/src/lib/rds-testimonial.component.ts
  raaghu-elements/src/rds-testimonial/src/lib/rds-testimonial.stories.ts
  raaghu-elements/src/rds-toasts/src/lib/toasts.md
  raaghu-elements/src/rds-website-metric/src/lib/website-metric.md
  raaghu-elements/src/root/styles-storybook.scss
  raaghu-mfe/angular.json
  raaghu-mfe/gatsby/src/assets/css/main.css
  raaghu-mfe/gatsby/src/components/Banners.js
  raaghu-mfe/gatsby/src/components/Elements.js
  raaghu-mfe/gatsby/src/components/Maincomp.js
  raaghu-mfe/gatsby/src/components/Navbar.js
  raaghu-mfe/gatsby/src/components/Sidebar.js
  raaghu-mfe/gatsby/src/pages/{markdownRemark.frontmatter__slug}.js
Labels: bug, ASP.net

#790 storybook pages enhancement
  raaghu-mfe/projects/rds-components/src/app/rdc-comp-api-scope-basics/rdc-comp-api-scope-basics.component.html
  raaghu-mfe/projects/rds-components/src/app/rdc-comp-api-scope-resources/rdc-comp-api-scope-resources.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-address-input/rds-comp-address-input.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-basic-resource/rds-comp-basic-resource.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-claims/rds-comp-claims.component.html
  raaghu-mfe/projects/rds-page-api-scope/src/app/api-scope.stories.ts
  raaghu-mfe/projects/rds-page-claim-types/src/app/claim-types/claim-types.stories.ts
  raaghu-mfe/projects/rds-page-client/src/app/client.stories.ts
  raaghu-mfe/projects/rds-page-identity-resources/src/app/Identity-resources.stories.ts
  raaghu-mfe/projects/rds-page-identity-resources/src/app/app.component.ts
Labels: bug, enhancement, storybook

#811 Pricing table,Collapse&accordion
  raaghu-elements/src/rds-accordion/src/lib/accordion-item/accordion-item.component.html
  raaghu-elements/src/rds-accordion/src/lib/accordion-item/accordion-item.component.ts
  raaghu-elements/src/rds-accordion/src/lib/accordion.stories.ts
  raaghu-elements/src/rds-collapse/src/lib/collapse.stories.ts
  raaghu-elements/src/rds-collapse/src/lib/rds-collapse.component.html
  raaghu-elements/src/rds-collapse/src/lib/rds-collapse.component.ts
  raaghu-elements/src/rds-collapse/src/lib/rds-collapse.module.ts
  raaghu-elements/src/rds-dropdown/src/lib/rds-dropdown.component.html
  raaghu-elements/src/rds-table/src/lib/rds-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-pricing-table/pricing-table.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-pricing-table/rds-comp-pricing-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
Labels: bug

#819 Accordian icon issue in demo-ui fixed,Audit logs page is not displaying. #813---
  raaghu-elements/src/rds-accordion/src/lib/accordion-item/accordion-item.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
Labels: bug

#820 UI alignment bugs
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
Labels: bug

#822 committed changes for gatsby build issue
  raaghu-mfe/gatsby/gatsby-config.js
  raaghu-mfe/gatsby/src/components/Sidebar.js
  raaghu-mfe/gatsby/static/images/Landing page-Pages/api-resources.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/api-scope.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/audit-log.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/cart.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/claim-types.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/client.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/dashboard.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/dynamic-property-management.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/edition.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/identity-resources.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/language-text.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/language.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/maintenance.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/organization-unit.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/role.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/security-log.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/settings.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/tenant.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/text-template.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/under-construction.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/under-maintenance.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/user.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/visual-settings.png
  raaghu-mfe/gatsby/static/images/Landing page-Pages/webhook-subscriptions.png
Labels: gatsby

#825 Bug Fixes- #799, #800, #799, #802, #803, #810
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.html
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.html
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.html
Labels: bug, ASP.net

#827 #809,#749(pricing table,Audit-logs,feature-list)
  raaghu-elements/src/rds-button/src/lib/rds-button.component.html
  raaghu-elements/src/rds-feature-list/src/lib/feature-list.stories.ts
  raaghu-elements/src/rds-feature-list/src/lib/rds-feature-list.component.html
  raaghu-elements/src/rds-feature-list/src/lib/rds-feature-list.component.ts
  raaghu-elements/src/rds-feature-list/src/lib/rds-feature-list.module.ts
  raaghu-elements/src/rds-icon/src/lib/rds-icon.component.ts
  raaghu-elements/src/rds-label/src/lib/rds-label.component.ts
  raaghu-elements/src/rds-table/src/lib/rds-table.component.html
  raaghu-elements/src/rds-table/src/lib/rds-table.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-pricing-table/pricing-table.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-pricing-table/rds-comp-pricing-table.component.html
Labels: bug

#831 Skeleton added for the elements and chart section on landing page.
  .gitignore
  raaghu-elements/src/rds-alert/src/lib/alert.md
  raaghu-elements/src/rds-benefit/src/lib/benefit.md
  raaghu-elements/src/rds-big-number-widget/src/lib/big-number-widget.md
  raaghu-elements/src/rds-breadcrumb/src/lib/breadcrumb.md
  raaghu-elements/src/rds-button/src/lib/button.md
  raaghu-elements/src/rds-chart-line/src/lib/chart-line.md
  raaghu-elements/src/rds-checkbox-groups/src/lib/checkbox-groups.md
  raaghu-elements/src/rds-checkbox-parent-child/src/lib/checkbox-parent-child.md
  raaghu-elements/src/rds-color-picker/src/lib/color-picker.md
  raaghu-elements/src/rds-datepicker/src/lib/datepicker.md
  raaghu-elements/src/rds-double-range/src/lib/double-range.md
  raaghu-elements/src/rds-dropdownlist/src/lib/dropdownlist.md
  raaghu-elements/src/rds-icon-label/src/lib/icon-label.md
  raaghu-elements/src/rds-icon/src/lib/icon.md
  raaghu-elements/src/rds-illustration/src/lib/illustration.md
  raaghu-elements/src/rds-input-group/src/lib/input-group.md
  raaghu-elements/src/rds-input/src/lib/input.md
  raaghu-elements/src/rds-textarea/src/lib/textarea.md
  raaghu-elements/src/rds-toasts/src/lib/toasts.md
  raaghu-mfe/gatsby/src/assets/data/elements.json
  raaghu-mfe/gatsby/static/images/Landing page-Elements/area-chart.png
  raaghu-mfe/gatsby/static/images/Landing page-Elements/bar-chart.png
  raaghu-mfe/gatsby/static/images/Landing page-Elements/boolean-chart.png
  raaghu-mfe/gatsby/static/images/Landing page-Elements/bubble-chart.png
  raaghu-mfe/gatsby/static/images/Landing page-Elements/doughnut-chart.png
  raaghu-mfe/gatsby/static/images/Landing page-Elements/line-chart.png
  raaghu-mfe/gatsby/static/images/Landing page-Elements/mixed-chart.png
  raaghu-mfe/gatsby/static/images/Landing page-Elements/pie-chart.png
  raaghu-mfe/gatsby/static/images/Landing page-Elements/polar-area-chart.png
  raaghu-mfe/gatsby/static/images/Landing page-Elements/radar-chart.png
  raaghu-mfe/gatsby/static/images/Landing page-Elements/scatter-chart.png
  raaghu-mfe/gatsby/static/images/Landing page-Elements/stacked-chart.png
  raaghu-mfe/gatsby/static/images/big-number-widget-skeleton.png
  raaghu-mfe/gatsby/static/images/checkbox-group-parent-child-skeleton.png
  raaghu-mfe/gatsby/static/images/checkbox-group-skeleton.png
  raaghu-mfe/gatsby/static/images/color-picker-skeleton.png
  raaghu-mfe/gatsby/static/images/date-picker-skeleton.png
  raaghu-mfe/gatsby/static/images/double-range-skeleton.png
  raaghu-mfe/gatsby/static/images/double-range-type1.png
  raaghu-mfe/gatsby/static/images/double-range-type2.png
  raaghu-mfe/gatsby/static/images/double-range.png
  raaghu-mfe/gatsby/static/images/dropdown-list-skeleton.png
  raaghu-mfe/gatsby/static/images/icon-skeleton.png
  raaghu-mfe/gatsby/static/images/illustration-skeleton.png
  raaghu-mfe/gatsby/static/images/input-group-skeleton.png
  raaghu-mfe/gatsby/static/images/input-skeleton.png
  raaghu-mfe/gatsby/static/images/linechart-default.png
  raaghu-mfe/gatsby/static/images/linechart-stepped.png
  raaghu-mfe/gatsby/static/images/skel-alert-banner.png
  raaghu-mfe/gatsby/static/images/skel-like_dislike.png
  raaghu-mfe/projects/stories/assets/Demo.gif
Labels: documentation, gatsby

#835 PR for #805 and #828
  raaghu-elements/src/rds-offcanvas/src/lib/offcanvas.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-mysettings/rds-comp-mysettings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-mysettings/rds-comp-mysettings.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basics/rds-comp-user-basics.component.html
  raaghu-mfe/projects/rds-page-organization-unit/src/app/app.component.html
Labels: bug, ASP.net

#836 data binding for users page
  raaghu-mfe/projects/host/src/app/app.module.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/state-management/src/lib/app.interface.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/language/language.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/language/language.selector.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/role/role.selector.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/user/user.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/user/user.reducer.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/user/user.selector.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-role/rds-comp-new-role.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basic-profile-right/rds-comp-user-basic-profile-right.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basic-profile-right/rds-comp-user-basic-profile-right.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions-new/rds-comp-user-permissions-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions-new/rds-comp-user-permissions-new.component.ts
  raaghu-mfe/projects/rds-page-user/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-user/src/app/app.module.ts
Labels: A B P

#844 comment of offcanvas extra code
  raaghu-elements/src/rds-offcanvas/src/lib/offcanvas.stories.ts
Labels: storybook

#837 Bug- Default theme for light mode - Host Admin #830
  raaghu-elements/src/rds-offcanvas/src/lib/offcanvas.stories.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.html
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/themes/src/styles/blue.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/libs/themes/src/styles/green.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
Labels: bug, ASP.net

#845 After creating new entry it should display on top of the table.#801
  raaghu-elements/src/rds-offcanvas/src/lib/rds-offcanvas.component.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/tenant/tenant.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/user/user.effects.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
  raaghu-mfe/projects/rds-page-maintenance/src/app/app.component.html
  raaghu-mfe/projects/rds-page-maintenance/src/app/app.component.scss
  raaghu-mfe/projects/rds-page-maintenance/src/app/app.component.ts
Labels: bug
