Repository Wai-Technologies/raaghu-angular, pull requests merged in 2022-08, with the labels that each got.

#103 Comp product overview
  .vs/VSWorkspaceState.json
  .vs/raaghu/v17/.suo
  .vs/raaghu/v17/workspaceFileList.bin
  raaghu-mfe/projects/rds-components/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-product-overview/product-overview.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-product-overview/rds-comp-product-overview.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-product-overview/rds-comp-product-overview.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-product-overview/rds-comp-product-overview.component.spec.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-product-overview/rds-comp-product-overview.component.ts
Labels: enhancement

#149 Development
  raaghu-elements/src/rds-modal/src/lib/modal.stories.ts
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.scss
  raaghu-elements/src/rds-tags/src/lib/rds-tags.component.html
  raaghu-mfe/package.json
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-dynamic-entity-property/rds-comp-new-dynamic-entity-property.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-organization-tree/rds-comp-organization-tree.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-visual-settings/rds-comp-visual-settings.component.ts
Labels: bug

#155 Bug fixes
  raaghu-elements/src/rds-datepicker/src/lib/datepicker.stories.ts
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.html
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.ts
  raaghu-elements/tsconfig.json
  raaghu-mfe/projects/host/src/index.html
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/organization-unit/src/app/app.component.html
  raaghu-mfe/projects/organization-unit/src/app/app.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.ts
  raaghu-mfe/projects/tenant/src/app/app.component.ts
  raaghu-mfe/projects/user/src/app/app.component.ts
Labels: Bug-#72-#97

#164 Development
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.ts
Labels: bug

#167 Development
  raaghu-elements/angular.json
  raaghu-elements/src/rds-accordion/src/lib/accordion-item/accordion-item.component.html
  raaghu-elements/src/rds-accordion/src/lib/accordion-item/accordion-item.component.scss
  raaghu-elements/src/rds-accordion/src/lib/accordion-item/accordion-item.component.ts
  raaghu-elements/src/rds-accordion/src/lib/accordion.stories.ts
  raaghu-elements/src/rds-accordion/src/lib/rds-accordian.module.ts
  raaghu-elements/src/rds-accordion/src/lib/rds-accordion.component.ts
  raaghu-elements/src/rds-accordion/src/lib/rds-accordion.service.ts
  raaghu-mfe/projects/rds-components/src/app/app.module.ts
Labels: enhancement, Display Type

#169 Development
  raaghu-elements/src/rds-badge/src/lib/badge.stories.ts
  raaghu-elements/src/rds-badge/src/lib/rds-badge.module.ts
  raaghu-elements/src/rds-benefit/src/lib/benefit.stories.ts
  raaghu-elements/src/rds-benefit/src/lib/rds-benefit.component.ts
  raaghu-elements/src/rds-rating/src/lib/rds-rating.component.html
  raaghu-elements/src/rds-review-category/src/lib/rds-review-category.component.html
  raaghu-elements/src/rds-review-category/src/lib/rds-review-category.component.ts
  raaghu-elements/src/rds-review-category/src/lib/rds-review-category.module.ts
  raaghu-elements/src/rds-review-category/src/lib/review-category.stories.ts
  raaghu-elements/tsconfig.json
  raaghu-mfe/projects/rds-components/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-benefit/benefit.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-benefit/rds-comp-benefit.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-review-category/rds-comp-review-category.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-review-category/rds-comp-review-category.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-review-category/rds-comp-review-category.component.spec.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-review-category/rds-comp-review-category.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-review-category/review-category.stories.ts
  raaghu-mfe/tsconfig.json
  raaghu-mfe/utils/sync-elements.js
Labels: Feature-Review-Category

#171 Development
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-information/rds-comp-information.component.html
Labels: Bug #121-#150

#175 Development
  raaghu-elements/src/rds-big-number-widget/src/lib/rds-big-number-widget.component.ts
  raaghu-elements/src/rds-chart-bool/src/lib/rds-chart-bool.component.ts
  raaghu-elements/src/rds-widget/src/lib/rds-widget.component.ts
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/libs/themes/src/styles/default.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.ts
Labels: enhancement

#176 Development
  raaghu-elements/src/rds-modal/src/lib/modal.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-information/rds-comp-information.component.html
Labels: bug

#204 Users and Roles change
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.ts
  raaghu-mfe/projects/role/src/app/app.component.ts
  raaghu-mfe/projects/user/src/app/app.component.ts
Labels: bug

#195 Development
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/default.scss
  raaghu-mfe/projects/libs/themes/src/styles/side-nav.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.ts
Labels: enhancement

#196 Development
  raaghu-elements/src/rds-accordion/src/lib/accordion-item/accordion-item.component.html
  raaghu-elements/src/rds-accordion/src/lib/accordion-item/accordion-item.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-product-overview/product-overview.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-product-overview/rds-comp-product-overview.component.html
Labels: bug

#199 Development
  raaghu-elements/src/rds-benefit/src/lib/benefit.stories.ts
  raaghu-elements/src/rds-benefit/src/lib/rds-benefit.component.html
  raaghu-elements/src/rds-benefit/src/lib/rds-benefit.component.ts
  raaghu-mfe/projects/login/src/app/app.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-benefit/benefit.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-benefit/rds-comp-benefit.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.html
Labels: enhancement

#205 Development
  raaghu-elements/angular.json
  raaghu-elements/src/public-api.ts
  raaghu-elements/src/rds-icon/src/lib/icon.stories.ts
  raaghu-elements/src/rds-icon/src/lib/rds-icon.component.ts
  raaghu-elements/src/rds-like-dislike/src/lib/rds-like-dislike.component.html
  raaghu-elements/src/rds-progressbar/src/lib/progressbar.stories.ts
  raaghu-elements/src/rds-progressbar/src/lib/rds-progressbar.component.html
  raaghu-elements/src/rds-progressbar/src/lib/rds-progressbar.component.ts
  raaghu-elements/src/rds-review-category/src/lib/rds-review-category.component.ts
  raaghu-mfe/projects/rds-components/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-customer-reviews/customer-reviews.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-customer-reviews/rds-comp-customer-reviews.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-customer-reviews/rds-comp-customer-reviews.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-customer-reviews/rds-comp-customer-reviews.component.spec.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-customer-reviews/rds-comp-customer-reviews.component.ts
  raaghu-mfe/projects/rds-components/webpack.config.js
Labels: enhancement

#209 Development
  raaghu-elements/src/rds-icon/src/assets/icons/eye-slash.svg
  raaghu-elements/src/rds-icon/src/assets/icons/eye.svg
  raaghu-elements/src/rds-icon/src/lib/icons.ts
  raaghu-elements/src/rds-input/src/lib/input.stories.ts
  raaghu-elements/src/rds-input/src/lib/rds-input.component.html
  raaghu-elements/src/rds-input/src/lib/rds-input.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.html
Labels: bug

#216 Development
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.html
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.ts
  raaghu-mfe/projects/language/src/app/app.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-language/new-language.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-language/rds-comp-new-language.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.scss
Labels: bug

#218 committed for page transitions
  raaghu-mfe/projects/audit-logs/src/app/app.component.html
  raaghu-mfe/projects/audit-logs/src/app/app.component.ts
  raaghu-mfe/projects/edition/src/app/app.component.html
  raaghu-mfe/projects/edition/src/app/app.component.ts
  raaghu-mfe/projects/edition/src/app/app.module.ts
  raaghu-mfe/projects/edition/webpack.config.js
  raaghu-mfe/projects/language/src/app/app.component.html
  raaghu-mfe/projects/language/src/app/app.component.ts
  raaghu-mfe/projects/language/src/app/app.module.ts
  raaghu-mfe/projects/libs/shared/src/lib/animation.ts
  raaghu-mfe/projects/role/src/app/app.component.html
  raaghu-mfe/projects/role/src/app/app.component.ts
  raaghu-mfe/projects/role/src/app/app.module.ts
  raaghu-mfe/projects/settings/src/app/app.component.html
  raaghu-mfe/projects/settings/src/app/app.component.ts
  raaghu-mfe/projects/tenant/src/app/app.component.html
  raaghu-mfe/projects/tenant/src/app/app.component.ts
  raaghu-mfe/projects/user/src/app/app.component.html
  raaghu-mfe/projects/user/src/app/app.component.ts
  raaghu-mfe/projects/user/src/app/app.module.ts
  raaghu-mfe/projects/visual-settings/src/app/app.component.html
  raaghu-mfe/projects/visual-settings/src/app/app.component.ts
  raaghu-mfe/projects/visual-settings/src/app/app.module.ts
Labels: enhancement

#219 Development
  raaghu-elements/src/rds-select-list/src/lib/select-list.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-visual-settings/rds-comp-visual-settings.component.html
Labels: bug

#221 Development
  raaghu-mfe/projects/rds-components/src/app/rds-comp-organization-tree/rds-comp-organization-tree.component.html
Labels: bug

#226 Development
  raaghu-elements/src/rds-stepper/src/lib/rds-stepper.stories.ts
  raaghu-mfe/projects/demo-ui/src/app/demo-ui/demo-ui.component.html
  raaghu-mfe/projects/demo-ui/src/app/demo-ui/demo-ui.component.ts
  raaghu-mfe/projects/dynamic-property-management/src/app/app.component.html
  raaghu-mfe/projects/dynamic-property-management/src/app/app.component.ts
  raaghu-mfe/projects/dynamic-property-management/src/app/app.module.ts
  raaghu-mfe/projects/organization-unit/src/app/app.component.html
  raaghu-mfe/projects/organization-unit/src/app/app.component.ts
  raaghu-mfe/projects/organization-unit/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-benefit/benefit.stories.ts
  raaghu-mfe/projects/settings/src/app/app.component.html
  raaghu-mfe/projects/settings/src/app/app.component.ts
  raaghu-mfe/projects/settings/src/app/app.module.ts
  raaghu-mfe/projects/webhooksubscription/src/app/app.component.html
  raaghu-mfe/projects/webhooksubscription/src/app/app.component.ts
  raaghu-mfe/projects/webhooksubscription/src/app/app.module.ts
  raaghu-mfe/projects/webhooksubscription/src/app/webhooksubscription/webhooksubscription.component.ts
Labels: enhancement

#228 Development
  raaghu-elements/src/rds-carousel/src/lib/carousel.stories.ts
  raaghu-elements/src/rds-carousel/src/lib/rds-carousel.component.html
  raaghu-elements/src/rds-carousel/src/lib/rds-carousel.component.scss
  raaghu-elements/src/rds-carousel/src/lib/rds-carousel.component.ts
  raaghu-elements/src/rds-carousel/src/lib/rds-carousel.module.ts
Labels: enhancement

#232 Development
  raaghu-elements/angular.json
  raaghu-elements/src/rds-product-image/src/lib/rds-product-image.component.html
  raaghu-elements/src/rds-product-image/src/lib/rds-product-image.component.scss
  raaghu-elements/src/rds-product-image/src/lib/rds-product-image.component.ts
  raaghu-elements/src/rds-team-member/.browserslistrc
  raaghu-elements/src/rds-team-member/README.md
  raaghu-elements/src/rds-team-member/karma.conf.js
  raaghu-elements/src/rds-team-member/ng-package.json
  raaghu-elements/src/rds-team-member/package.json
  raaghu-elements/src/rds-team-member/src/lib/rds-team-member.component.html
  raaghu-elements/src/rds-team-member/src/lib/rds-team-member.component.scss
  raaghu-elements/src/rds-team-member/src/lib/rds-team-member.component.spec.ts
  raaghu-elements/src/rds-team-member/src/lib/rds-team-member.component.ts
  raaghu-elements/src/rds-team-member/src/lib/rds-team-member.module.ts
  raaghu-elements/src/rds-team-member/src/lib/rds-team-member.service.spec.ts
  raaghu-elements/src/rds-team-member/src/lib/rds-team-member.service.ts
  raaghu-elements/src/rds-team-member/src/lib/team-member.stories.ts
  raaghu-elements/src/rds-team-member/src/public-api.ts
  raaghu-elements/src/rds-team-member/src/test.ts
  raaghu-elements/src/rds-team-member/tsconfig.lib.json
  raaghu-elements/src/rds-team-member/tsconfig.lib.prod.json
  raaghu-elements/src/rds-team-member/tsconfig.spec.json
Labels: enhancement

#233 Development
  raaghu-elements/src/rds-dropdown/src/lib/dropdown.stories.ts
  raaghu-elements/src/rds-dropdown/src/lib/rds-dropdown.component.ts
  raaghu-elements/src/rds-dropdownlist/src/lib/dropdownlist.stories.ts
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.ts
  raaghu-elements/src/rds-icon/src/lib/icons.ts
  raaghu-elements/src/rds-illustration/src/lib/rds-illustration.component.html
  raaghu-elements/src/rds-pagination/src/lib/rds-pagination.component.html
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.html
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/maintenance/src/app/maintenance/maintenance.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-alert/rds-comp-alert.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-cache/rds-comp-cache.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-email/rds-comp-email.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-website-log/rds-comp-website-log.component.html
  raaghu-mfe/projects/securitylog/src/app/app.component.html
  raaghu-mfe/projects/settings/src/app/app.component.html
Labels: icon-updation

#234 Order details page
  raaghu-elements/src/rds-address-detail/src/lib/rds-address-detail.component.ts
  raaghu-elements/src/rds-card-detail/src/lib/rds-card-detail.component.html
  raaghu-elements/src/rds-card-detail/src/lib/rds-card-detail.component.ts
  raaghu-elements/src/rds-card-detail/src/lib/rds-card-detail.module.ts
  raaghu-mfe/angular.json
  raaghu-mfe/projects/host/src/app/app.routes.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/order-details/order-details.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/order-details/order-details.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/order-details/order-details.models.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/order-details/order-details.reducers.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/order-details/order-details.selectors.ts
  raaghu-mfe/projects/mfe-config.ts
  raaghu-mfe/projects/order-details/.browserslistrc
  raaghu-mfe/projects/order-details/karma.conf.js
  raaghu-mfe/projects/order-details/src/app/app-routing.module.ts
  raaghu-mfe/projects/order-details/src/app/app.component.html
  raaghu-mfe/projects/order-details/src/app/app.component.scss
  raaghu-mfe/projects/order-details/src/app/app.component.spec.ts
  raaghu-mfe/projects/order-details/src/app/app.component.ts
  raaghu-mfe/projects/order-details/src/app/app.module.ts
  raaghu-mfe/projects/order-details/src/assets/.gitkeep
  raaghu-mfe/projects/order-details/src/bootstrap.ts
  raaghu-mfe/projects/order-details/src/environments/environment.prod.ts
  raaghu-mfe/projects/order-details/src/environments/environment.ts
  raaghu-mfe/projects/order-details/src/favicon.ico
  raaghu-mfe/projects/order-details/src/index.html
  raaghu-mfe/projects/order-details/src/main.ts
  raaghu-mfe/projects/order-details/src/polyfills.ts
  raaghu-mfe/projects/order-details/src/styles.scss
  raaghu-mfe/projects/order-details/src/test.ts
  raaghu-mfe/projects/order-details/tsconfig.app.json
  raaghu-mfe/projects/order-details/tsconfig.spec.json
  raaghu-mfe/projects/order-details/webpack.config.js
  raaghu-mfe/projects/order-details/webpack.prod.config.js
  raaghu-mfe/projects/rds-components/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-order-details/order-details.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-order-details/rds-comp-order-details.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-order-details/rds-comp-order-details.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-order-details/rds-comp-order-details.component.spec.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-order-details/rds-comp-order-details.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-review-category/rds-comp-review-category.component.html
  raaghu-mfe/projects/rds-components/webpack.config.js
Labels: enhancement

#235 Development
  raaghu-elements/src/rds-icon/src/lib/rds-icon.component.ts
  raaghu-elements/src/rds-rating/src/lib/rating.stories.ts
  raaghu-elements/src/rds-rating/src/lib/rds-rating.component.html
  raaghu-elements/src/rds-rating/src/lib/rds-rating.component.scss
  raaghu-elements/src/rds-rating/src/lib/rds-rating.component.ts
  raaghu-elements/src/rds-review-category/src/lib/rds-review-category.component.html
  raaghu-elements/src/rds-review-category/src/lib/rds-review-category.module.ts
  raaghu-elements/src/rds-review-category/src/lib/review-category.stories.ts
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-customer-reviews/rds-comp-customer-reviews.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-customer-reviews/rds-comp-customer-reviews.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.html
Labels: bug

#237 Development
  raaghu-mfe/projects/dashboard/src/app/app-routing.module.ts
  raaghu-mfe/projects/dashboard/src/app/auth.guard.ts
  raaghu-mfe/projects/host/src/app/app.routes.ts
  raaghu-mfe/projects/libs/shared/src/lib/auth.guard.ts
  raaghu-mfe/projects/login/src/app/app.component.ts
Labels: bug

#238 Development
  raaghu-elements/src/rds-icon/src/lib/flag-icons.ts
  raaghu-elements/src/rds-icon/src/lib/icons.ts
  raaghu-elements/src/rds-icon/src/lib/rds-icon.component.ts
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.html
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/language/src/app/app.component.html
  raaghu-mfe/projects/language/src/app/app.component.ts
  raaghu-mfe/projects/language/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-billing/rds-comp-billing.component.ts
  raaghu-mfe/projects/subscription/src/app/app.component.ts
Labels: icon-updation

#240 Development
  raaghu-mfe/projects/rds-components/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-testimonials/rds-comp-testimonials.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-testimonials/rds-comp-testimonials.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-testimonials/rds-comp-testimonials.component.spec.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-testimonials/rds-comp-testimonials.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-testimonials/testimonials.stories.ts
Labels: feature-testimonial

#241 committed for page transitions
  raaghu-mfe/projects/audit-logs/src/app/app.component.ts
  raaghu-mfe/projects/demo-ui/src/app/app-routing.module.ts
  raaghu-mfe/projects/demo-ui/src/app/app.component.html
  raaghu-mfe/projects/demo-ui/src/app/app.component.ts
  raaghu-mfe/projects/demo-ui/src/app/app.module.ts
  raaghu-mfe/projects/demo-ui/src/app/demo-ui/demo-ui.component.html
  raaghu-mfe/projects/demo-ui/src/app/demo-ui/demo-ui.component.scss
  raaghu-mfe/projects/demo-ui/src/app/demo-ui/demo-ui.component.spec.ts
  raaghu-mfe/projects/demo-ui/src/app/demo-ui/demo-ui.component.ts
  raaghu-mfe/projects/edition/src/app/app.component.ts
  raaghu-mfe/projects/language/src/app/app.component.ts
  raaghu-mfe/projects/maintenance/src/app/app-routing.module.ts
  raaghu-mfe/projects/maintenance/src/app/app.component.html
  raaghu-mfe/projects/maintenance/src/app/app.component.ts
  raaghu-mfe/projects/maintenance/src/app/app.module.ts
  raaghu-mfe/projects/maintenance/src/app/cache/cache.component.html
  raaghu-mfe/projects/maintenance/src/app/cache/cache.component.scss
  raaghu-mfe/projects/maintenance/src/app/cache/cache.component.spec.ts
  raaghu-mfe/projects/maintenance/src/app/cache/cache.component.ts
  raaghu-mfe/projects/maintenance/src/app/maintenance/maintenance.component.html
  raaghu-mfe/projects/maintenance/src/app/maintenance/maintenance.component.scss
  raaghu-mfe/projects/maintenance/src/app/maintenance/maintenance.component.spec.ts
  raaghu-mfe/projects/maintenance/src/app/maintenance/maintenance.component.ts
  raaghu-mfe/projects/maintenance/src/app/maintenance/rds-maintenance-shimmer/rds-maintenance-shimmer.component.html
  raaghu-mfe/projects/maintenance/src/app/maintenance/rds-maintenance-shimmer/rds-maintenance-shimmer.component.scss
  raaghu-mfe/projects/maintenance/src/app/maintenance/rds-maintenance-shimmer/rds-maintenance-shimmer.component.spec.ts
  raaghu-mfe/projects/maintenance/src/app/maintenance/rds-maintenance-shimmer/rds-maintenance-shimmer.component.ts
  raaghu-mfe/projects/maintenance/src/app/websitelog/websitelog.component.html
  raaghu-mfe/projects/maintenance/src/app/websitelog/websitelog.component.scss
  raaghu-mfe/projects/maintenance/src/app/websitelog/websitelog.component.spec.ts
  raaghu-mfe/projects/maintenance/src/app/websitelog/websitelog.component.ts
  raaghu-mfe/projects/organization-unit/src/app/app.component.html
  raaghu-mfe/projects/organization-unit/src/app/app.component.ts
  raaghu-mfe/projects/organization-unit/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-website-log/rds-comp-website-log.component.ts
  raaghu-mfe/projects/role/src/app/app.component.ts
  raaghu-mfe/projects/settings/src/app/app.component.ts
  raaghu-mfe/projects/tenant/src/app/app.component.ts
  raaghu-mfe/projects/user/src/app/app.component.ts
  raaghu-mfe/projects/visual-settings/src/app/app.component.ts
  raaghu-mfe/projects/webhooksubscription/src/app/app.component.ts
Labels: enhancement

#248 Development
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-app-details/rds-comp-app-details.component.html
Labels: enhancement

#250 Development
  raaghu-elements/src/public-api.ts
  raaghu-elements/src/rds-team-member/src/lib/rds-team-member.component.html
  raaghu-elements/src/rds-team-member/src/lib/rds-team-member.component.ts
  raaghu-elements/src/rds-team-member/src/lib/rds-team-member.module.ts
  raaghu-elements/src/rds-team-member/src/lib/team-member.stories.ts
  raaghu-elements/src/root/public-api.ts
  raaghu-mfe/angular.json
  raaghu-mfe/projects/maintenance/src/app/maintenance.stories.ts
  raaghu-mfe/projects/rds-components/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-teams/rds-comp-teams.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-teams/rds-comp-teams.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-teams/rds-comp-teams.component.spec.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-teams/rds-comp-teams.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-teams/teams.stories.ts
  raaghu-mfe/projects/rds-components/webpack.config.js
  raaghu-mfe/tsconfig.json
  raaghu-mfe/utils/sync-elements.js
Labels: enhancement

#280 resolve bugs
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/host/src/assets/profile-picture-circle.svg
  raaghu-mfe/projects/host/src/assets/profile-picture.svg
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/libs/themes/src/styles/dropdown.scss
  raaghu-mfe/projects/maintenance/src/app/maintenance/maintenance.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
Labels: bug

#277 Development
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
Labels: bug

#256 Development
  raaghu-elements/angular.json
  raaghu-elements/src/public-api.ts
  raaghu-elements/src/rds-carousel/src/lib/rds-carousel.component.html
  raaghu-elements/src/rds-carousel/src/lib/rds-carousel.module.ts
  raaghu-elements/src/rds-testimonial/.browserslistrc
  raaghu-elements/src/rds-testimonial/README.md
  raaghu-elements/src/rds-testimonial/karma.conf.js
  raaghu-elements/src/rds-testimonial/ng-package.json
  raaghu-elements/src/rds-testimonial/package.json
  raaghu-elements/src/rds-testimonial/src/lib/rds-testimonial.component.html
  raaghu-elements/src/rds-testimonial/src/lib/rds-testimonial.component.scss
  raaghu-elements/src/rds-testimonial/src/lib/rds-testimonial.component.spec.ts
  raaghu-elements/src/rds-testimonial/src/lib/rds-testimonial.component.ts
  raaghu-elements/src/rds-testimonial/src/lib/rds-testimonial.module.ts
  raaghu-elements/src/rds-testimonial/src/lib/rds-testimonial.service.spec.ts
  raaghu-elements/src/rds-testimonial/src/lib/rds-testimonial.service.ts
  raaghu-elements/src/rds-testimonial/src/lib/rds-testimonial.stories.ts
  raaghu-elements/src/rds-testimonial/src/public-api.ts
  raaghu-elements/src/rds-testimonial/src/test.ts
  raaghu-elements/src/rds-testimonial/tsconfig.lib.json
  raaghu-elements/src/rds-testimonial/tsconfig.lib.prod.json
  raaghu-elements/src/rds-testimonial/tsconfig.spec.json
  raaghu-elements/src/root/public-api.ts
  raaghu-mfe/projects/rds-components/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-testimonials/rds-comp-testimonials.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-testimonials/rds-comp-testimonials.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-testimonials/testimonials.stories.ts
Labels: element-creation

#267 Development
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.html
  raaghu-mfe/projects/tenant/src/app/app.component.ts
Labels: bug

#263 Development
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.html
  raaghu-elements/src/rds-icon/src/lib/icons.ts
  raaghu-mfe/angular.json
  raaghu-mfe/projects/contact-us/.browserslistrc
  raaghu-mfe/projects/contact-us/karma.conf.js
  raaghu-mfe/projects/contact-us/src/app/app-routing.module.ts
  raaghu-mfe/projects/contact-us/src/app/app.component.html
  raaghu-mfe/projects/contact-us/src/app/app.component.scss
  raaghu-mfe/projects/contact-us/src/app/app.component.spec.ts
  raaghu-mfe/projects/contact-us/src/app/app.component.ts
  raaghu-mfe/projects/contact-us/src/app/app.module.ts
  raaghu-mfe/projects/contact-us/src/assets/.gitkeep
  raaghu-mfe/projects/contact-us/src/bootstrap.ts
  raaghu-mfe/projects/contact-us/src/environments/environment.prod.ts
  raaghu-mfe/projects/contact-us/src/environments/environment.ts
  raaghu-mfe/projects/contact-us/src/favicon.ico
  raaghu-mfe/projects/contact-us/src/index.html
  raaghu-mfe/projects/contact-us/src/main.ts
  raaghu-mfe/projects/contact-us/src/polyfills.ts
  raaghu-mfe/projects/contact-us/src/styles.scss
  raaghu-mfe/projects/contact-us/src/test.ts
  raaghu-mfe/projects/contact-us/tsconfig.app.json
  raaghu-mfe/projects/contact-us/tsconfig.spec.json
  raaghu-mfe/projects/contact-us/webpack.config.js
  raaghu-mfe/projects/contact-us/webpack.prod.config.js
  raaghu-mfe/projects/host/src/app/app.routes.ts
  raaghu-mfe/projects/host/src/assets/contact.svg
  raaghu-mfe/projects/libs/state-management/src/lib/state/contact-us/contact-us.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/contact-us/contact-us.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/contact-us/contact-us.models.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/contact-us/contact-us.reducers.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/contact-us/contact-us.selectors.ts
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/mfe-config.ts
  raaghu-mfe/projects/rds-components/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-contact-us/rds-comp-contact-us.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-contact-us/rds-comp-contact-us.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-contact-us/rds-comp-contact-us.component.spec.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-contact-us/rds-comp-contact-us.component.ts
  raaghu-mfe/projects/rds-components/webpack.config.js
Labels: feature/contact-us

#262 Enhancement in order details page.
  raaghu-elements/src/public-api.ts
  raaghu-elements/src/rds-progressbar/src/lib/rds-progressbar.component.html
  raaghu-elements/src/rds-progressbar/src/lib/rds-progressbar.component.ts
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.html
  raaghu-mfe/projects/host/src/app/app.routes.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/order-details/src/app/app.component.ts
  raaghu-mfe/projects/rds-components/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-customer-reviews/rds-comp-customer-reviews.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-customer-reviews/rds-comp-customer-reviews.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-order-details/order-details.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-order-details/rds-comp-order-details.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-order-details/rds-comp-order-details.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/top-navigation.stories.ts
  raaghu-mfe/projects/tenant/src/app/app.component.ts
Labels: enhancement

#260 commited-top & side navigation bar as per the FOI screen
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.html
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.html
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
Labels: enhancement

#301 Development
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/libs/themes/src/styles/dropdown.scss
  raaghu-mfe/projects/libs/themes/src/styles/green.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.html
Labels: bug

#299 Development
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.html
Labels: bug

#302 committed for pagination issue,collapse button ui
  raaghu-elements/src/public-api.ts
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.html
  raaghu-mfe/projects/host/src/app/app.routes.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/libs/themes/src/styles/pagination.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-order-details/order-details.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-webhook-subscription/rds-comp-webhook-subscription.component.html
Labels: bug, enhancement

#303 Development
  raaghu-elements/src/public-api.ts
  raaghu-elements/src/rds-avatar/src/lib/avatar.stories.ts
  raaghu-elements/src/rds-icon/src/lib/icon.stories.ts
  raaghu-elements/src/rds-icon/src/lib/icons.ts
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.html
  raaghu-elements/src/root/public-api.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-app-details/rds-comp-app-details.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-billing/billing.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-billing/rds-comp-billing.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-contact-us/contact-us.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-contact-us/rds-comp-contact-us.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-email-settings/email-settings.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-integration/integration.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-order-details/order-details.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-personal-info/personal-info.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/tsconfig.json
  raaghu-mfe/utils/sync-elements.js
Labels: icon-updation

#310 Development
  raaghu-elements/src/rds-team-member/src/lib/team-member.stories.ts
  raaghu-elements/tsconfig.json
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.html
Labels: bug

#312 Development
  raaghu-elements/src/public-api.ts
  raaghu-elements/src/root/public-api.ts
  raaghu-mfe/projects/rds-components/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-teams/rds-comp-teams.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-timeline/rds-comp-timeline.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-timeline/rds-comp-timeline.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-timeline/rds-comp-timeline.component.spec.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-timeline/rds-comp-timeline.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-timeline/timeline.stories.ts
  raaghu-mfe/tsconfig.json
  raaghu-mfe/utils/sync-elements.js
Labels: element-creation

#318 Development
  raaghu-elements/src/rds-counter/src/lib/rds-counter.component.html
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.html
  raaghu-elements/src/rds-icon/src/lib/icons.ts
  raaghu-mfe/projects/libs/themes/src/styles/badge.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-email/rds-comp-email.component.html
  raaghu-mfe/projects/settings/src/app/app.component.html
Labels: bug

#319 Development
  raaghu-elements/src/rds-button/src/lib/rds-button.component.html
  raaghu-elements/tsconfig.json
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/utils/sync-elements.js
Labels: bug

#320 Development
  raaghu-elements/src/rds-team-member/src/lib/rds-team-member.component.html
  raaghu-elements/src/rds-team-member/src/lib/rds-team-member.module.ts
  raaghu-elements/src/rds-team-member/src/lib/team-member.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-language/new-language.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.html
Labels: bug

#321 visual-settings page rendering issue
  raaghu-mfe/angular.json
Labels: bug

#322 Development
  raaghu-elements/src/rds-counter/src/lib/rds-counter.component.html
  raaghu-elements/src/rds-counter/src/lib/rds-counter.module.ts
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.html
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.ts
  raaghu-elements/tsconfig.json
  raaghu-mfe/projects/language/src/app/app.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-notification/rds-comp-notification.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.html
  raaghu-mfe/tsconfig.json
  raaghu-mfe/utils/sync-elements.js
Labels: bug

#323 Development
  raaghu-mfe/projects/host/src/assets/building_lights.mp4
  raaghu-mfe/projects/host/src/assets/raaghu-text.svg
  raaghu-mfe/projects/host/src/assets/raaghu_text_logo.svg
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/login/src/app/app.component.html
Labels: bug

#324 committed for UI changes in settings page
  raaghu-mfe/projects/rds-components/src/app/rds-comp-security/rds-comp-security.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-management/rds-comp-tenant-management.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-management/rds-comp-user-management.component.html
  raaghu-mfe/projects/role/src/app/app.component.ts
Labels: bug

#325 Development
  raaghu-elements/src/rds-input/src/lib/rds-input.component.html
  raaghu-elements/src/rds-offcanvas/src/lib/rds-offcanvas.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login-attempts/rds-comp-login-attempts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-mysettings/my-settings.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-mysettings/rds-comp-mysettings.component.html
Labels: bug

#327 Development
  raaghu-elements/src/rds-counter/src/lib/rds-counter.component.ts
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.html
Labels: bug

#328 Development
  raaghu-elements/angular.json
  raaghu-elements/src/rds-nav-tab/src/lib/rds-nav-tab.component.ts
  raaghu-elements/src/rds-stat/.browserslistrc
  raaghu-elements/src/rds-stat/README.md
  raaghu-elements/src/rds-stat/karma.conf.js
  raaghu-elements/src/rds-stat/ng-package.json
  raaghu-elements/src/rds-stat/package.json
  raaghu-elements/src/rds-stat/src/lib/rds-stat.component.html
  raaghu-elements/src/rds-stat/src/lib/rds-stat.component.scss
  raaghu-elements/src/rds-stat/src/lib/rds-stat.component.spec.ts
  raaghu-elements/src/rds-stat/src/lib/rds-stat.component.ts
  raaghu-elements/src/rds-stat/src/lib/rds-stat.module.ts
  raaghu-elements/src/rds-stat/src/lib/rds-stat.service.spec.ts
  raaghu-elements/src/rds-stat/src/lib/rds-stat.service.ts
  raaghu-elements/src/rds-stat/src/lib/rds-stat.stories.ts
  raaghu-elements/src/rds-stat/src/public-api.ts
  raaghu-elements/src/rds-stat/src/test.ts
  raaghu-elements/src/rds-stat/tsconfig.lib.json
  raaghu-elements/src/rds-stat/tsconfig.lib.prod.json
  raaghu-elements/src/rds-stat/tsconfig.spec.json
  raaghu-mfe/projects/rds-components/src/app/rds-comp-linked-accounts/rds-comp-linked-accounts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.ts
Labels: bug

#334 Development
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-linked-accounts/rds-comp-linked-accounts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-linked-accounts/rds-comp-linked-accounts.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login-attempts/rds-comp-login-attempts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login-attempts/rds-comp-login-attempts.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-mysettings/rds-comp-mysettings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-mysettings/rds-comp-mysettings.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-language/rds-comp-new-language.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-language/rds-comp-new-language.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-role/rds-comp-new-role.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-role/rds-comp-new-role.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-settings/rds-comp-tenant-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-settings/rds-comp-tenant-settings.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basics/rds-comp-user-basics.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-delegations/rds-comp-user-delegations.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-delegations/rds-comp-user-delegations.component.ts
Labels: bug

#336 changes made for login password field icon issue
  raaghu-elements/src/rds-icon/src/lib/rds-icon.component.ts
  raaghu-elements/src/rds-input/src/lib/rds-input.component.html
  raaghu-elements/src/rds-input/src/lib/rds-input.component.scss
  raaghu-elements/src/rds-input/src/lib/rds-input.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-order-details/order-details.stories.ts
Labels: bug

#338 Development
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.html
  raaghu-elements/src/rds-icon/src/lib/icons.ts
  raaghu-elements/src/rds-icon/src/lib/rds-icon.component.ts
  raaghu-elements/src/rds-illustration/src/lib/rds-illustration.component.html
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.html
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-cache/rds-comp-cache.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-email/rds-comp-email.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-linked-accounts/rds-comp-linked-accounts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-linked-accounts/rds-comp-linked-accounts.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-order-details/order-details.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-delegations/rds-comp-user-delegations.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-delegations/rds-comp-user-delegations.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-website-log/rds-comp-website-log.component.html
  raaghu-mfe/projects/settings/src/app/app.component.html
Labels: bug

#339 dynamic property api
  raaghu-mfe/projects/dynamic-property-management/src/app/app.component.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-information/rds-comp-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-information/rds-comp-information.component.ts
Labels: bug

#340 Development
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
Labels: bug

#341 Development
  raaghu-mfe/projects/rds-components/src/app/rds-comp-edition/rds-comp-edition.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-hierarchy/hierarchy.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-linked-accounts/rds-comp-linked-accounts.component.ts
Labels: bug

#342 Development
  raaghu-elements/src/rds-fab-menu/src/lib/fabmenu.stories.ts
  raaghu-elements/src/rds-fab-menu/src/lib/rds-fab-menu.component.html
  raaghu-elements/src/rds-fab-menu/src/lib/rds-fab-menu.component.ts
  raaghu-elements/src/rds-like-dislike/src/lib/rds-like-dislike.component.html
Labels: bug

#360 Bug : #349
  raaghu-mfe/projects/rds-components/src/app/rds-comp-linked-accounts/rds-comp-linked-accounts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-linked-accounts/rds-comp-linked-accounts.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-mysettings/rds-comp-mysettings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-mysettings/rds-comp-mysettings.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
Labels: bug
