Repository Wai-Technologies/raaghu-angular, pull requests merged in 2022-12, with the labels that each got.

#1181 PR for bug #1158
  raaghu-mfe/projects/host/src/assets/i18n/nl.json
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list-new/rds-comp-tenant-list-new.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-management/rds-comp-tenant-management.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-webhook-subscription/rds-comp-webhook-subscription.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-webhook-subscription/rds-comp-webhook-subscription.component.ts
  raaghu-mfe/projects/rds-page-dashboard/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-language/src/app/app.component.html
Labels: bug

#1182 Development
  raaghu-elements/src/rds-card/src/lib/rds-card.component.html
  raaghu-elements/src/rds-card/src/lib/rds-card.component.ts
  raaghu-elements/src/rds-widget/src/lib/rds-widget.component.html
  raaghu-elements/src/rds-widget/src/lib/rds-widget.component.ts
  raaghu-mfe/projects/libs/themes/src/styles/accessible.scss
  raaghu-mfe/projects/libs/themes/src/styles/card.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/default.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-linked-accounts/rds-comp-linked-accounts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login-attempts/rds-comp-login-attempts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-mysettings/rds-comp-mysettings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-features/rds-comp-tenant-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-management/rds-comp-tenant-management.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-settings/rds-comp-tenant-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-delegations/rds-comp-user-delegations.component.html
  raaghu-mfe/projects/rds-page-tenant/src/app/app.component.ts
Labels: bug, ASP.net

#1200 Host admin>>Permissions tab>>Roles>>Footer message should be same as wireframe. #
  raaghu-elements/src/rds-button/src/lib/rds-button.component.html
  raaghu-elements/src/rds-file-uploader/src/lib/rds-file-uploader.component.html
  raaghu-mfe/projects/libs/state-management/src/lib/state/login/login.selector.ts
  raaghu-mfe/projects/libs/themes/src/styles/accessible.scss
  raaghu-mfe/projects/libs/themes/src/styles/button.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-linked-accounts/rds-comp-linked-accounts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login-attempts/rds-comp-login-attempts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-mysettings/rds-comp-mysettings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-management/rds-comp-tenant-management.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-delegations/rds-comp-user-delegations.component.html
Labels: ASP.net

#1203 Dark and Light theme in storybook
  raaghu-elements/src/rds-address-detail/src/lib/address-detail.stories.ts
  raaghu-elements/src/rds-address-detail/src/lib/rds-address-detail.component.html
  raaghu-elements/src/rds-avatar/src/lib/avatar.stories.ts
  raaghu-elements/src/rds-badge/src/lib/badge.stories.ts
  raaghu-elements/src/rds-benefit/src/lib/benefit.stories.ts
  raaghu-elements/src/rds-button/src/lib/button.stories.ts
  raaghu-elements/src/rds-datepicker/src/lib/datepicker.stories.ts
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.html
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.scss
  raaghu-elements/src/rds-double-range/src/lib/rds-double-range.component.scss
  raaghu-elements/src/rds-dropdown/src/lib/dropdown.stories.ts
  raaghu-elements/src/rds-dropdown/src/lib/rds-dropdown.component.html
  raaghu-elements/src/rds-dropdown/src/lib/rds-dropdown.component.ts
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.html
  raaghu-elements/src/rds-fab-menu/src/lib/fabmenu.stories.ts
  raaghu-elements/src/rds-feature-list/src/lib/feature-list.stories.ts
  raaghu-elements/src/rds-feed/src/lib/rds-feed.component.html
  raaghu-elements/src/rds-icon-label/src/lib/icon-label.stories.ts
  raaghu-elements/src/rds-input-group/src/lib/input-group.stories.ts
  raaghu-elements/src/rds-input-group/src/lib/rds-input-group.component.ts
  raaghu-elements/src/rds-offcanvas/src/lib/offcanvas.stories.ts
  raaghu-elements/src/rds-offcanvas/src/lib/rds-offcanvas.component.scss
  raaghu-elements/src/rds-popover/src/lib/popover.stories.ts
  raaghu-elements/src/rds-price/src/lib/price.stories.ts
  raaghu-elements/src/rds-price/src/lib/rds-price.component.html
  raaghu-elements/src/rds-range/src/lib/rds-range.component.scss
  raaghu-elements/src/rds-review-category/src/lib/rds-review-category.component.html
  raaghu-elements/src/rds-search-input/src/lib/search-input.stories.ts
  raaghu-elements/src/rds-size/src/lib/rds-size.component.ts
  raaghu-elements/src/rds-size/src/lib/rds-size.stories.ts
  raaghu-elements/src/rds-stat/src/lib/rds-stat.component.html
  raaghu-elements/src/rds-stepper/src/lib/rds-stepper.component.scss
  raaghu-elements/src/rds-table/src/lib/rds-table.component.html
  raaghu-elements/src/rds-table/src/lib/table.stories.ts
  raaghu-elements/src/root/styles-storybook.scss
  raaghu-mfe/.storybook/main.js
  raaghu-mfe/.storybook/manager.js
  raaghu-mfe/.storybook/preview.js
  raaghu-mfe/package.json
  raaghu-mfe/projects/libs/themes/src/styles/accordion.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/table.scss
  raaghu-mfe/projects/libs/themes/src/styles/tags.scss
Labels: storybook

#1205 committed for tooltip and pagination bugs
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.html
  raaghu-mfe/projects/rds-page-settings/src/app/app.component.html
Labels: bug

#1210 theming issues
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables-dark.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables-light.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
Labels: storybook

#1189 PR for implement alert on login page and PR for bug #1109
  raaghu-mfe/projects/host/src/assets/i18n/ar.json
  raaghu-mfe/projects/host/src/assets/i18n/es.json
  raaghu-mfe/projects/host/src/assets/i18n/fr.json
  raaghu-mfe/projects/host/src/assets/i18n/it.json
  raaghu-mfe/projects/host/src/assets/i18n/nl.json
  raaghu-mfe/projects/host/src/assets/i18n/tr.json
  raaghu-mfe/projects/rds-page-login/src/app/app.component.html
  raaghu-mfe/projects/rds-page-login/src/app/app.component.scss
  raaghu-mfe/projects/rds-page-login/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-login/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-maintenance/src/app/app.component.html
  raaghu-mfe/projects/rds-page-maintenance/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-maintenance/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-webhooksubscription/src/app/app.component.html
  raaghu-mfe/projects/rds-page-webhooksubscription/src/app/app.component.ts
Labels: bug

#1219 bugs Fixed:#612,#1183,#918
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.ts
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.html
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.ts
  raaghu-elements/src/rds-side-nav/src/lib/side-nav.stories.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.html
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables-light.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-language/rds-comp-new-language.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-language/rds-comp-new-language.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.ts
  raaghu-mfe/projects/rds-page-language/src/app/app.component.ts
Labels: bug

#1222 Action added into elements storybook
  raaghu-elements/src/rds-accordion/src/lib/accordion.stories.ts
  raaghu-elements/src/rds-alert/src/lib/alert.stories.ts
  raaghu-elements/src/rds-badge/src/lib/badge.stories.ts
  raaghu-elements/src/rds-breadcrumb/src/lib/breadcrumb.stories.ts
  raaghu-elements/src/rds-button-group/src/lib/button-group.stories.ts
  raaghu-elements/src/rds-button/src/lib/button.stories.ts
  raaghu-elements/src/rds-button/src/lib/rds-button.component.ts
  raaghu-elements/src/rds-card-detail/src/lib/carddetail.stories.ts
  raaghu-elements/src/rds-checkbox-groups/src/lib/checkbox-groups.stories.ts
  raaghu-elements/src/rds-checkbox-parent-child/src/lib/checkbox-parent-child.stories.ts
  raaghu-elements/src/rds-checkbox/src/lib/checkbox.stories.ts
  raaghu-elements/src/rds-collapse/src/lib/collapse.stories.ts
  raaghu-elements/src/rds-color-picker/src/lib/color-picker.stories.ts
  raaghu-elements/src/rds-color/src/lib/color.stories.ts
  raaghu-elements/src/rds-counter/src/lib/counter.stories.ts
  raaghu-elements/src/rds-datepicker/src/lib/datepicker.stories.ts
  raaghu-elements/src/rds-double-range/src/lib/double-range.stories.ts
  raaghu-elements/src/rds-dropdown/src/lib/dropdown.stories.ts
  raaghu-elements/src/rds-dropdownlist/src/lib/dropdownlist.stories.ts
  raaghu-elements/src/rds-fab-menu/src/lib/fabmenu.stories.ts
  raaghu-elements/src/rds-feed/src/lib/feed.stories.ts
  raaghu-elements/src/rds-file-uploader/src/lib/file-uploader.stories.ts
  raaghu-elements/src/rds-input-group/src/lib/input-group.stories.ts
  raaghu-elements/src/rds-like-dislike/src/lib/like-dislike.stories.ts
  raaghu-elements/src/rds-list-group/src/lib/list-group.stories.ts
  raaghu-elements/src/rds-modal/src/lib/modal.stories.ts
  raaghu-elements/src/rds-nav-bar/src/lib/nav-bar.stories.ts
  raaghu-elements/src/rds-nav-tab/src/lib/nav-tab.stories.ts
  raaghu-elements/src/rds-offcanvas/src/lib/offcanvas.stories.ts
  raaghu-elements/src/rds-pagination/src/lib/pagination.stories.ts
  raaghu-elements/src/rds-popover/src/lib/popover.stories.ts
  raaghu-elements/src/rds-radio-button/src/lib/radio-button.stories.ts
  raaghu-elements/src/rds-range/src/lib/range.stories.ts
  raaghu-elements/src/rds-review-category/src/lib/review-category.stories.ts
  raaghu-elements/src/rds-search-input/src/lib/search-input.stories.ts
  raaghu-elements/src/rds-select-list/src/lib/select-list.stories.ts
  raaghu-elements/src/rds-side-nav/src/lib/side-nav.stories.ts
  raaghu-elements/src/rds-size/src/lib/rds-size.stories.ts
  raaghu-elements/src/rds-website-metric/src/lib/website-metric.stories.ts
  raaghu-elements/src/rds-widget/src/lib/widget.stories.ts
Labels: storybook

#1223 PR for internationalization of Mexican, Russian, Thai, and Chinese languages.
  raaghu-mfe/projects/host/src/assets/i18n/es-MX.json
  raaghu-mfe/projects/host/src/assets/i18n/ru.json
  raaghu-mfe/projects/host/src/assets/i18n/th.json
  raaghu-mfe/projects/host/src/assets/i18n/zh-Hans.json
Labels: bug

#1230 Committed for language translation
  raaghu-mfe/projects/host/src/assets/i18n/af-NA.json
  raaghu-mfe/projects/host/src/assets/i18n/am-ET.json
  raaghu-mfe/projects/host/src/assets/i18n/de.json
  raaghu-mfe/projects/host/src/assets/i18n/en-GB.json
  raaghu-mfe/projects/host/src/assets/i18n/en.json
  raaghu-mfe/projects/host/src/assets/i18n/nl.json
  raaghu-mfe/projects/host/src/assets/i18n/pt-BR.json
  raaghu-mfe/projects/host/src/assets/i18n/vi.json
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-enity-properties/rds-comp-dynamic-enity-properties.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list-new/rds-comp-tenant-list-new.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions-new/rds-comp-user-permissions-new.component.ts
  raaghu-mfe/projects/rds-page-dynamic-property-management/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-dynamic-property-management/src/app/dynamic-property-management.stories.ts
  raaghu-mfe/projects/rds-page-dynamic-property-management/src/dynamic-property-management.md
Labels: Angular

#1247 Bug Fixed:#1232
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.html
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.scss
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.html
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables-dark.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables-light.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
Labels: bug

#1254 Host admin>>Tenant>>Edition>>Webhooksubscripiton>>Unable to see newly created records.
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-webhook-subscription/rds-comp-webhook-subscription.component.ts
  raaghu-mfe/projects/rds-page-maintenance/src/app/app.component.html
  raaghu-mfe/projects/rds-page-user/src/app/app.component.html
  raaghu-mfe/projects/rds-page-webhooksubscription/src/app/app.component.ts
Labels: bug, ASP.net, Angular

#1258 Development component restructure : dynamic property page changes
  raaghu-mfe/projects/libs/state-management/src/lib/state/dynamic-property-management/dynamic-property.effects.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-enity-properties/rds-comp-dynamic-enity-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-dynamic-entity-property/rds-comp-new-dynamic-entity-property.component.html
  raaghu-mfe/projects/rds-page-dynamic-property-management/src/app/app.component.html
  raaghu-mfe/projects/rds-page-dynamic-property-management/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-maintenance/src/app/app.component.html
  raaghu-mfe/projects/rds-page-maintenance/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-maintenance/src/app/app.module.ts
Labels: bug, ASP.net, Angular

#1256 Development : Dashboard>>Monthly summary chart.
  raaghu-elements/angular.json
  raaghu-elements/src/public-api.ts
  raaghu-elements/src/rds-dropdown/src/lib/dropdown.stories.ts
  raaghu-elements/src/rds-dropdown/src/lib/rds-dropdown.component.html
  raaghu-elements/src/rds-dropdown/src/lib/rds-dropdown.component.ts
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.html
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.ts
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.module.ts
  raaghu-elements/src/rds-side-nav/src/lib/side-nav.stories.ts
  raaghu-elements/src/rds-toggle/.browserslistrc
  raaghu-elements/src/rds-toggle/README.md
  raaghu-elements/src/rds-toggle/karma.conf.js
  raaghu-elements/src/rds-toggle/ng-package.json
  raaghu-elements/src/rds-toggle/package.json
  raaghu-elements/src/rds-toggle/src/lib/rds-toggle.component.html
  raaghu-elements/src/rds-toggle/src/lib/rds-toggle.component.scss
  raaghu-elements/src/rds-toggle/src/lib/rds-toggle.component.spec.ts
  raaghu-elements/src/rds-toggle/src/lib/rds-toggle.component.ts
  raaghu-elements/src/rds-toggle/src/lib/rds-toggle.module.ts
  raaghu-elements/src/rds-toggle/src/lib/rds-toggle.service.spec.ts
  raaghu-elements/src/rds-toggle/src/lib/rds-toggle.service.ts
  raaghu-elements/src/rds-toggle/src/lib/toggle.stories.ts
  raaghu-elements/src/rds-toggle/src/public-api.ts
  raaghu-elements/src/rds-toggle/src/test.ts
  raaghu-elements/src/rds-toggle/tsconfig.lib.json
  raaghu-elements/src/rds-toggle/tsconfig.lib.prod.json
  raaghu-elements/src/rds-toggle/tsconfig.spec.json
  raaghu-elements/src/root/public-api.ts
  raaghu-elements/src/root/styles-storybook.scss
  raaghu-elements/tsconfig.json
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/host/src/assets/DarkTheme.png
  raaghu-mfe/projects/host/src/assets/LightTheme.png
  raaghu-mfe/projects/host/src/assets/accessibleTheme.png
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/libs/themes/src/styles/offcanvas.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-visual-settings/rds-comp-visual-settings.component.html
  raaghu-mfe/tsconfig.json
  raaghu-mfe/utils/sync-elements.js
Labels: bug, ASP.net

#1257 Bug Fixed:1249--
  raaghu-elements/src/rds-chart-bool/src/lib/rds-chart-bool.component.ts
  raaghu-elements/src/rds-chart-doughnut/src/lib/rds-chart-doughnut.component.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.ts
  raaghu-mfe/projects/rds-page-tenant/src/app/app.component.ts
Labels: bug

#1289 Modification and renaming of storybook elements
  raaghu-elements/src/rds-accordion/src/lib/accordion.stories.ts
  raaghu-elements/src/rds-address-detail/src/lib/rds-address-detail.component.html
  raaghu-elements/src/rds-address-detail/src/lib/rds-address-detail.component.scss
  raaghu-elements/src/rds-avatar/src/lib/avatar.stories.ts
  raaghu-elements/src/rds-avatar/src/lib/rds-avatar.component.html
  raaghu-elements/src/rds-badge/src/lib/badge.stories.ts
  raaghu-elements/src/rds-badge/src/lib/rds-badge.component.scss
  raaghu-elements/src/rds-badge/src/lib/rds-badge.component.ts
  raaghu-elements/src/rds-benefit/src/lib/benefit.stories.ts
  raaghu-elements/src/rds-card/src/lib/rds-card.component.html
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.scss
  raaghu-elements/src/rds-double-range/src/lib/double-range.stories.ts
  raaghu-elements/src/rds-double-range/src/lib/rds-double-range.component.html
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.ts
  raaghu-elements/src/rds-feature-list/src/lib/rds-feature-list.component.html
  raaghu-elements/src/rds-nav-bar/src/lib/rds-nav-bar.component.html
  raaghu-elements/src/rds-product-image/src/lib/rds-product-image.stories.ts
  raaghu-elements/src/rds-range/src/lib/range.stories.ts
  raaghu-elements/src/rds-range/src/lib/rds-range.component.html
  raaghu-elements/src/rds-range/src/lib/rds-range.component.scss
  raaghu-elements/src/rds-range/src/lib/rds-range.component.ts
  raaghu-elements/src/rds-stepper/src/lib/rds-stepper.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-resources/client-resources.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-marketing-website-newsletter/marketingwebsitenewsletter.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-marketing-website-newsletter/rds-comp-marketing-website-newsletter.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-marketing-website-newsletter/rds-comp-marketing-website-newsletter.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-product-overview/product-overview.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-review-category/review-category.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/tenant.information.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-delegations/rds-comp-user-delegations.component.html
Labels: bug, storybook, Angular

#1280 committed for settings page
  raaghu-mfe/projects/host/src/app/app.module.ts
  raaghu-mfe/projects/host/src/app/app.routes.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/settings/settings.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/settings/settings.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/settings/settings.reducer.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/settings/settings.selector.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-account-new/account.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-account-new/rds-comp-account-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-account-new/rds-comp-account-new.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-email-settings-new/rds-comp-email-settings-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-email-settings-new/rds-comp-email-settings-new.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-identity-management-new/rds-comp-identity-management-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-identity-management-new/rds-comp-identity-management-new.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-settings-new/rds-comp-settings-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-settings-new/rds-comp-settings-new.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-settings-new/settings-new.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-theme-new/rds-comp-theme-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-theme-new/rds-comp-theme-new.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-theme-new/theme.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
  raaghu-mfe/projects/rds-components/webpack.config.js
  raaghu-mfe/projects/rds-page-demo-ui/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-settings/src/app/app.component.html
  raaghu-mfe/projects/rds-page-settings/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-settings/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-settings/src/app/settings.stories.ts
Labels: A B P

#1284 Development
  raaghu-mfe/projects/host/src/app/app.component.ts
  raaghu-mfe/projects/libs/themes/src/styles/accessible.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables-dark.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables-light.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-visual-settings/rds-comp-visual-settings.component.html
Labels: bug, ASP.net

#1293 committed changes for back to tenant functionality
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.html
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/mla/mla.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/mla/mla.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/mla/mla.reducer.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/mla/mla.selector.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.module.ts
Labels: bug, ASP.net

#1299 Bugs Fixed:1285,1287,1288,1244,1264----
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/webhook-subscription/webhook-subscription.effects.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs-new/rds-comp-audit-logs-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login-attempts/rds-comp-login-attempts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-member-activity/rds-comp-member-activity.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-language/rds-comp-new-language.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-notification/rds-comp-notification.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list-new/rds-comp-tenant-list-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-delegations/rds-comp-user-delegations.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions-new/rds-comp-user-permissions-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-table/rds-comp-user-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-webhook-subscription/rds-comp-webhook-subscription.component.html
  raaghu-mfe/projects/rds-page-language/src/app/app.component.html
  raaghu-mfe/projects/rds-page-language/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-organization-unit/src/app/app.component.html
  raaghu-mfe/projects/rds-page-tenant/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-user/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-webhooksubscription/src/app/app.component.html
  raaghu-mfe/projects/rds-page-webhooksubscription/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-webhooksubscription/src/app/app.module.ts
Labels: bug

#1300 PR for role page restructuring
  raaghu-mfe/projects/rds-page-role/src/app/app.component.html
  raaghu-mfe/projects/rds-page-role/src/app/app.component.scss
  raaghu-mfe/projects/rds-page-role/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-role/src/app/app.module.ts
Labels: bug

#1302 Storybook changes
  raaghu-elements/src/rds-accordion/src/lib/accordion-item/accordion-item.component.html
  raaghu-elements/src/rds-address-detail/src/lib/rds-address-detail.component.html
  raaghu-elements/src/rds-app-details/src/lib/app-details.stories.ts
  raaghu-elements/src/rds-app-details/src/lib/rds-app-details.component.html
  raaghu-elements/src/rds-avatar/src/lib/rds-avatar.component.html
  raaghu-elements/src/rds-badge/src/lib/badge.stories.ts
  raaghu-elements/src/rds-benefit/src/lib/rds-benefit.component.html
  raaghu-elements/src/rds-big-number-widget/src/lib/big-number-widget.stories.ts
  raaghu-elements/src/rds-big-number-widget/src/lib/rds-big-number-widget.component.ts
  raaghu-elements/src/rds-card-detail/src/lib/rds-card-detail.component.html
  raaghu-elements/src/rds-card/src/lib/card.stories.ts
  raaghu-elements/src/rds-dropdownlist/src/lib/dropdownlist.stories.ts
  raaghu-elements/src/rds-feature-list/src/lib/rds-feature-list.component.html
  raaghu-elements/src/rds-range/src/lib/rds-range.component.scss
  raaghu-elements/src/rds-range/src/lib/rds-range.component.ts
  raaghu-elements/src/rds-review-category/src/lib/rds-review-category.component.html
  raaghu-elements/src/rds-scrollspy/src/lib/rds-scrollspy.component.html
  raaghu-elements/src/rds-scrollspy/src/lib/scrollspy.stories.ts
  raaghu-elements/src/rds-select-list/src/lib/rds-select-list.component.ts
  raaghu-elements/src/rds-size/src/lib/rds-size.component.html
  raaghu-elements/src/rds-stepper/src/lib/rds-stepper.stories.ts
  raaghu-elements/src/rds-table/src/lib/rds-table.component.ts
  raaghu-elements/src/rds-table/src/lib/table.stories.ts
  raaghu-elements/src/rds-team-member/src/lib/rds-team-member.component.html
  raaghu-elements/src/rds-team-member/src/lib/rds-team-member.component.scss
  raaghu-elements/src/rds-team-member/src/lib/team-member.stories.ts
  raaghu-elements/src/rds-widget/src/lib/rds-widget.component.ts
  raaghu-elements/src/rds-widget/src/lib/widget.stories.ts
  raaghu-mfe/projects/libs/themes/src/styles/accordion.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables-dark.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables-light.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
  raaghu-mfe/projects/rds-page-api-resources/src/app/api-resources.stories.ts
  raaghu-mfe/projects/rds-page-api-scope/src/app/api-scope.stories.ts
  raaghu-mfe/projects/rds-page-client/src/app/client.stories.ts
  raaghu-mfe/projects/rds-page-infinite-product-list/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-infinite-product-list/src/app/infinite-product-list.stories.ts
  raaghu-mfe/projects/rds-page-webhooksubscription/src/app/webhooksubscription.stories.ts
Labels: bug, storybook, Angular

#1315 Fixed responsive bugs
  raaghu-elements/src/rds-nav-tab/src/lib/rds-nav-tab.component.html
  raaghu-elements/src/rds-pagination/src/lib/rds-pagination.component.scss
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables-dark.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables-light.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/cookieconsent.scss
  raaghu-mfe/projects/libs/themes/src/styles/side-nav.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-linked-accounts/rds-comp-linked-accounts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-delegations/rds-comp-user-delegations.component.html
Labels: bug, UI Design

#1314 Offcanvas spacing issue.
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-download-collection/rds-comp-download-collection.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-dynamic-entity-property/rds-comp-new-dynamic-entity-property.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-role/rds-comp-new-role.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-settings/rds-comp-tenant-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basics/rds-comp-user-basics.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-webhook-subscription/rds-comp-webhook-subscription.component.html
Labels: bug, ASP.net, Angular

#1320 tenant page restructuring
  raaghu-mfe/.npmrc
  raaghu-mfe/projects/libs/state-management/src/lib/state/tenant/tenant.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/tenant/tenant.effects.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.ts
  raaghu-mfe/projects/rds-page-tenant/src/app/app.component.html
  raaghu-mfe/projects/rds-page-tenant/src/app/app.component.scss
  raaghu-mfe/projects/rds-page-tenant/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-tenant/src/app/app.module.ts
Labels: enhancement, ASP.net, Angular

#1322 Bugs fixed: Role Alert,#1297,#1067
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.html
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.ts
  raaghu-mfe/projects/host/src/app/app.module.ts
  raaghu-mfe/projects/libs/shared/src/lib/http.interceptor.ts
  raaghu-mfe/projects/libs/state-management/src/lib/app.interface.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/role/role.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/role/role.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/role/role.reducer.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/role/role.selector.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.module.ts
  raaghu-mfe/projects/rds-page-audit-logs/src/app/app.component.html
  raaghu-mfe/projects/rds-page-audit-logs/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-audit-logs/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-role/src/app/app.component.html
  raaghu-mfe/projects/rds-page-role/src/app/app.component.ts
Labels: bug

#1323 committed changes for login page alert popup rendering issue bug - #1316
  raaghu-mfe/projects/rds-page-login/src/app/app.component.html
  raaghu-mfe/projects/rds-page-login/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-login/src/app/app.module.ts
Labels: bug, ASP.net, Angular

#1324 committed changes for adding input property for icon element for animate class - bug - #1303
  raaghu-elements/src/rds-icon/src/lib/icon.stories.ts
  raaghu-elements/src/rds-icon/src/lib/rds-icon.component.ts
  raaghu-elements/src/root/styles-storybook.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
Labels: bug, Angular

#1325 fixed responsive bugs
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.html
  raaghu-mfe/projects/rds-page-role/src/app/app.component.html
Labels: bug

#1327 committed changes for subscription page rendering issue
  raaghu-mfe/projects/rds-components/src/app/rds-comp-subscription/rds-comp-subscription.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-subscription/rds-comp-subscription.component.ts
  raaghu-mfe/projects/rds-page-subscription/src/app/app.component.html
  raaghu-mfe/projects/rds-page-subscription/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-subscription/src/app/app.module.ts
Labels: bug, Angular

#1328 Bug Fixed:#985--
  raaghu-mfe/projects/rds-page-audit-logs/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-demo-ui/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-dynamic-property-management/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-edition/src/app/app.component.html
  raaghu-mfe/projects/rds-page-edition/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-language/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-maintenance/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-organization-unit/src/app/app.component.html
  raaghu-mfe/projects/rds-page-organization-unit/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-role/src/app/app.component.html
  raaghu-mfe/projects/rds-page-role/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-settings/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-tenant/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-user/src/app/app.component.html
  raaghu-mfe/projects/rds-page-user/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-visual-settings/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-webhooksubscription/src/app/app.component.ts
Labels: bug

#1329 Fixed responsive bugs on audit log page
  raaghu-mfe/projects/rds-page-audit-logs/src/app/app.component.html
Labels: bug

#1330 changes in datepicker
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.html
  raaghu-elements/src/rds-stepper/src/lib/rds-stepper.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-resources/client-resources.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-review-category/review-category.stories.ts
  raaghu-mfe/projects/rds-page-demo-ui/src/app/app.module.ts
Labels: bug, ASP.net, Angular

#1332 committed changes for removing mfe-loader from e-commerce pages
  raaghu-mfe/angular.json
  raaghu-mfe/projects/mfe-config.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-order-details/rds-comp-order-details.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-order-details/rds-comp-order-details.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-product-list/rds-comp-product-list.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-product-overview/rds-comp-product-overview.component.ts
  raaghu-mfe/projects/rds-page-careers/src/app/app.component.html
  raaghu-mfe/projects/rds-page-careers/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-careers/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-cart/src/app/app.component.html
  raaghu-mfe/projects/rds-page-cart/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-cart/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-cart/webpack.config.js
  raaghu-mfe/projects/rds-page-contact-us/src/app/app.component.html
  raaghu-mfe/projects/rds-page-contact-us/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-contact-us/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-contact-us/webpack.config.js
  raaghu-mfe/projects/rds-page-frequently-asked-questions/src/app/app.component.html
  raaghu-mfe/projects/rds-page-frequently-asked-questions/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-frequently-asked-questions/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-frequently-asked-questions/webpack.config.js
  raaghu-mfe/projects/rds-page-infinite-product-list/src/app/app.component.html
  raaghu-mfe/projects/rds-page-infinite-product-list/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-infinite-product-list/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-infinite-product-list/webpack.config.js
  raaghu-mfe/projects/rds-page-member-activity/src/app/app.component.html
  raaghu-mfe/projects/rds-page-member-activity/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-member-activity/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-order-details/src/app/app.component.html
  raaghu-mfe/projects/rds-page-order-details/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-order-details/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-order-details/webpack.config.js
  raaghu-mfe/projects/rds-page-order-summary/src/app/app.component.html
  raaghu-mfe/projects/rds-page-order-summary/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-order-summary/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-order-summary/webpack.config.js
  raaghu-mfe/projects/rds-page-page-not-found/src/app/app.component.html
  raaghu-mfe/projects/rds-page-page-not-found/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-page-not-found/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-page-not-found/webpack.config.js
  raaghu-mfe/projects/rds-page-product-details/src/app/app.component.html
  raaghu-mfe/projects/rds-page-product-details/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-product-details/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-product-details/webpack.config.js
  raaghu-mfe/projects/rds-page-store-front/src/app/app.component.html
  raaghu-mfe/projects/rds-page-store-front/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-store-front/src/app/app.module.ts
Labels: enhancement, Angular

#1336 Bugs fixed:#1311,#1326--
  raaghu-elements/src/rds-chart-bool/src/lib/rds-chart-bool.component.ts
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-alert-popup/alert-popup.md
  raaghu-mfe/projects/rds-components/src/app/rds-comp-alert-popup/alert-popup.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-alert-popup/rds-comp-alert-popup.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-alert-popup/rds-comp-alert-popup.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-cache/rds-comp-cache.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-organization-tree/rds-comp-organization-tree.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.html
  raaghu-mfe/projects/rds-page-maintenance/src/app/app.component.html
Labels: bug

#1337 Development abp
  raaghu-mfe/projects/libs/state-management/src/lib/state/api-resources/api-resources.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/clients/clients.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/clients/clients.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/identity-resources/identity-resources.effects.ts
  raaghu-mfe/projects/rds-components/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-claim-type-role/rds-comp-claim-type-role.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-advanced/rds-comp-client-advanced.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-advanced/rds-comp-client-advanced.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-basics/rds-comp-client-basics.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-basics/rds-comp-client-basics.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-basics/rds-comp-client-basics.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-resources/rds-comp-client-resources.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-resources/rds-comp-client-resources.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-resources/rds-comp-client-resources.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-secrets/rds-comp-secrets.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-secrets/rds-comp-secrets.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-secrets/rds-comp-secrets.module.ts
  raaghu-mfe/projects/rds-components/webpack.config.js
  raaghu-mfe/projects/rds-page-client/src/app/app.component.html
  raaghu-mfe/projects/rds-page-client/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-client/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-client/webpack.config.js
  raaghu-mfe/projects/rds-page-role/src/app/app.component.html
Labels: enhancement, A B P, Angular

#1340 committed for identity resources page for save and delete
  raaghu-mfe/projects/host/src/app/app.routes.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/identity-resources/identity-resources.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/identity-resources/identity-resources.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/identity-resources/identity-resources.reducer.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/identity-resources/identity-resources.selector.ts
  raaghu-mfe/projects/rds-components/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rdc-comp-api-scope-basics/rdc-comp-api-scope-basics.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-basic-resource/basic-resource.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-basic-resource/rds-comp-basic-resource.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-basic-resource/rds-comp-basic-resource.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-basic-resource/rds-comp-basic-resources.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-claim-type-role/rds-comp-claim-type-role.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-claims/rds-comp-claims.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-resources/rds-comp-client-resources.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-resources/rds-comp-client-resources.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-role/rds-comp-new-role.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-role/rds-comp-new-role.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-properties/rds-comp-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-properties/rds-comp-properties.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-properties/rds-comp-properties.module.ts
  raaghu-mfe/projects/rds-components/webpack.config.js
  raaghu-mfe/projects/rds-page-identity-resources/src/app/app.component.html
  raaghu-mfe/projects/rds-page-identity-resources/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-identity-resources/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-identity-resources/src/app/basicresource/basicresource.component.html
  raaghu-mfe/projects/rds-page-identity-resources/src/app/basicresource/basicresource.component.ts
  raaghu-mfe/projects/rds-page-identity-resources/src/app/claims/claims.component.html
  raaghu-mfe/projects/rds-page-identity-resources/src/app/claims/claims.component.ts
  raaghu-mfe/projects/rds-page-identity-resources/src/app/properties/properties.component.html
  raaghu-mfe/projects/rds-page-identity-resources/src/app/properties/properties.component.ts
  raaghu-mfe/projects/rds-page-identity-resources/webpack.config.js
  raaghu-mfe/tsconfig.json
Labels: A B P

#1343 committed for data table module
  raaghu-mfe/projects/rds-components/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-alert-popup/rds-comp-alert-popup.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-alert-popup/rds-comp-alert-popup.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-apply-for-position/rds-comp-apply-for-position.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-apply-for-position/rds-comp-apply-for-position.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs-new/rds-comp-audit-logs-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-billing/rds-comp-billing.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-advanced/rds-comp-client-advanced.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-advanced/rds-comp-client-advanced.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-advanced/rds-comp-client-advanced.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-resources/rds-comp-client-resources.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/data-table.md
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-enity-properties/dynamic-enity-properties.md
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-enity-properties/rds-comp-dynamic-enity-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-enity-properties/rds-comp-dynamic-enity-properties.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-enity-properties/rds-comp-dynamic-enity-properties.component.spec.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-enity-properties/rds-comp-dynamic-enity-properties.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/dynamic-properties.md
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/dynamic-properties.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.spec.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features-list-new/rds-comp-features-list-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-language-text-list/rds-comp-language-text-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-linked-accounts/rds-comp-linked-accounts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login-attempts/rds-comp-login-attempts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-member-activity/rds-comp-member-activity.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-organization-tree/rds-comp-organization-tree.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-properties/rds-comp-properties.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list-new/rds-comp-tenant-list-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-delegations/rds-comp-user-delegations.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions-new/rds-comp-user-permissions-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-webhook-subscription/rds-comp-webhook-subscription.component.html
  raaghu-mfe/projects/rds-components/webpack.config.js
  raaghu-mfe/projects/rds-page-api-scope/src/app/app.component.html
  raaghu-mfe/projects/rds-page-identity-resources/src/app/app.component.html
  raaghu-mfe/projects/rds-page-identity-resources/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-identity-resources/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-language/src/app/app.component.html
  raaghu-mfe/projects/rds-page-language/src/app/app.module.ts
Labels: A B P

#1338 changes in calendar dropdown issue
  raaghu-elements/src/rds-button-group/src/lib/button-group.stories.ts
  raaghu-elements/src/rds-card-detail/src/lib/carddetail.stories.ts
  raaghu-elements/src/rds-card-detail/src/lib/rds-card-detail.component.html
  raaghu-elements/src/rds-card-detail/src/lib/rds-card-detail.component.ts
  raaghu-elements/src/rds-card/src/lib/rds-card.component.ts
  raaghu-elements/src/root/styles-storybook.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-calendar/rds-comp-calendar.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-calendar/rds-comp-calendar.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/edition.list.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-management/rds-comp-user-management.module.ts
Labels: bug, ASP.net, Angular

#1346 Storybook UI issues fixes
  raaghu-elements/src/rds-accordion/src/lib/accordion.stories.ts
  raaghu-elements/src/rds-alert/src/lib/rds-alert.component.html
  raaghu-elements/src/rds-app-details/src/lib/rds-app-details.component.html
  raaghu-elements/src/rds-breadcrumb/src/lib/rds-breadcrumb.component.html
  raaghu-elements/src/rds-button/src/lib/rds-button.component.html
  raaghu-elements/src/rds-button/src/lib/rds-button.component.scss
  raaghu-elements/src/rds-button/src/lib/rds-button.component.ts
  raaghu-elements/src/rds-card-detail/src/lib/rds-card-detail.component.html
  raaghu-elements/src/rds-checkbox-groups/src/lib/rds-checkbox-groups.component.html
  raaghu-elements/src/rds-checkbox-groups/src/lib/rds-checkbox-groups.component.ts
  raaghu-elements/src/rds-checkbox-parent-child/src/lib/rds-checkbox-parent-child.component.html
  raaghu-elements/src/rds-collapse/src/lib/collapse.stories.ts
  raaghu-elements/src/rds-collapse/src/lib/rds-collapse.component.html
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.html
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.scss
  raaghu-elements/src/rds-file-uploader/src/lib/file-uploader.stories.ts
  raaghu-elements/src/rds-file-uploader/src/lib/rds-file-uploader.component.html
  raaghu-elements/src/rds-file-uploader/src/lib/rds-file-uploader.component.ts
  raaghu-elements/src/rds-icon-label/src/lib/icon-label.stories.ts
  raaghu-elements/src/rds-icon-label/src/lib/rds-icon-label.component.html
  raaghu-elements/src/rds-icon-label/src/lib/rds-icon-label.component.ts
  raaghu-elements/src/rds-illustration/src/lib/rds-illustration.component.html
  raaghu-elements/src/rds-nav-bar/src/lib/rds-nav-bar.component.html
  raaghu-elements/src/rds-nav-tab/src/lib/nav-tab.stories.ts
  raaghu-elements/src/rds-nav-tab/src/lib/rds-nav-tab.component.html
  raaghu-elements/src/rds-offcanvas/src/lib/rds-offcanvas.component.html
  raaghu-elements/src/rds-pagination/src/lib/rds-pagination.component.html
  raaghu-elements/src/rds-popular-pages/src/lib/rds-popular-pages.component.html
  raaghu-elements/src/rds-popular-pages/src/lib/rds-popular-pages.component.scss
  raaghu-elements/src/rds-price/src/lib/rds-price.component.html
  raaghu-elements/src/rds-review-category/src/lib/rds-review-category.component.html
  raaghu-elements/src/rds-scrollspy/src/lib/rds-scrollspy.component.html
  raaghu-elements/src/rds-scrollspy/src/lib/rds-scrollspy.module.ts
  raaghu-elements/src/rds-scrollspy/src/lib/scrollspy-item/scrollspy-item.component.html
  raaghu-elements/src/rds-scrollspy/src/lib/scrollspy.stories.ts
  raaghu-elements/src/rds-search-input/src/lib/rds-search-input.component.scss
  raaghu-elements/src/rds-select-list/src/lib/rds-select-list.component.html
  raaghu-elements/src/rds-size/src/lib/rds-size.component.html
  raaghu-elements/src/rds-stat/src/lib/rds-stat.component.html
  raaghu-elements/src/rds-stat/src/lib/rds-stat.component.scss
  raaghu-elements/src/rds-stat/src/lib/rds-stat.stories.ts
  raaghu-elements/src/rds-stepper/src/lib/rds-stepper.component.html
  raaghu-elements/src/rds-stepper/src/lib/rds-stepper.component.scss
  raaghu-elements/src/rds-tags/src/lib/rds-tags.component.html
  raaghu-elements/src/rds-testimonial/src/lib/rds-testimonial.component.html
  raaghu-elements/src/rds-website-metric/src/lib/rds-website-metric.component.html
  raaghu-elements/src/rds-website-metric/src/lib/rds-website-metric.component.scss
  raaghu-elements/src/root/styles-storybook.scss
  raaghu-mfe/gatsby/src/assets/css/style-elements.css
  raaghu-mfe/projects/host/src/index.html
  raaghu-mfe/projects/libs/themes/src/styles/carousel.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables-dark.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables-light.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/libs/themes/src/styles/pagination.scss
Labels: bug, ASP.net, Angular

#1354 Development abp for language and api-scope
  raaghu-mfe/projects/host/src/app/app.routes.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/api-scope/api-scope-action.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/api-scope/api-scope-effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/api-scope/api-scope.reducer.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/api-scope/api-scope.selector.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/language/language.selector.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-basic-resource/rds-comp-basic-resource.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-basic-resource/rds-comp-basic-resource.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-language-new/rds-comp-language-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-language-new/rds-comp-language-new.component.ts
  raaghu-mfe/projects/rds-page-api-scope/src/app/app.component.html
  raaghu-mfe/projects/rds-page-api-scope/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-api-scope/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-language/src/app/app.component.ts
Labels: A B P, Angular

#1352 Development abp
  raaghu-mfe/projects/libs/state-management/src/lib/state/clients/clients.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/clients/clients.effects.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-basics/rds-comp-client-basics.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-secrets/rds-comp-secrets.component.ts
  raaghu-mfe/projects/rds-page-client/src/app/app.component.html
  raaghu-mfe/projects/rds-page-client/src/app/app.component.ts
Labels: enhancement, A B P, Angular

#1356 Api resources intergartion done
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/api-resources/api-resources.effects.ts
  raaghu-mfe/projects/rds-components/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-basic-resource/rds-comp-basic-resource.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-basic-resource/rds-comp-basic-resource.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-basic-resource/rds-comp-basic-resources.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-resources/rds-comp-client-resources.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-properties/rds-comp-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-properties/rds-comp-properties.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-secrets/rds-comp-secrets.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-secrets/rds-comp-secrets.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-secrets/rds-comp-secrets.module.ts
  raaghu-mfe/projects/rds-page-api-resources/src/app/app.component.html
  raaghu-mfe/projects/rds-page-api-resources/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-api-resources/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-api-resources/webpack.config.js
  raaghu-mfe/projects/rds-page-identity-resources/src/app/app.component.html
  raaghu-mfe/projects/rds-page-identity-resources/src/app/app.component.ts
Labels: A B P

#1358 Development abp > API-Scope and Api-resources
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.html
  raaghu-mfe/projects/libs/state-management/src/lib/state/api-resources/api-resources.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/api-resources/api-resources.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/api-scope/api-scope-action.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/api-scope/api-scope-effects.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-basic-resource/rds-comp-basic-resource.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-basic-resource/rds-comp-basic-resource.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-notification/rds-comp-notification.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-properties/rds-comp-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-properties/rds-comp-properties.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-secrets/rds-comp-secrets.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-secrets/rds-comp-secrets.component.ts
  raaghu-mfe/projects/rds-page-api-resources/src/app/app.component.html
  raaghu-mfe/projects/rds-page-api-resources/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-api-resources/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-api-scope/src/app/app.component.html
  raaghu-mfe/projects/rds-page-api-scope/src/app/app.component.ts
Labels: A B P

#1360 Development abp for Api-scope and api-resources UI
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-basic-resource/rds-comp-basic-resource.component.html
  raaghu-mfe/projects/rds-page-api-resources/src/app/app.component.html
  raaghu-mfe/projects/rds-page-api-resources/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-api-resources/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-api-scope/src/app/app.component.html
  raaghu-mfe/projects/rds-page-api-scope/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-api-scope/src/app/app.module.ts
Labels: A B P
