Repository Wai-Technologies/raaghu-angular, pull requests merged in 2022-11, with the labels that each got.

#864 Edition page
  raaghu-mfe/projects/host/src/assets/appconfig.json
  raaghu-mfe/projects/libs/state-management/src/lib/state/DownloadData/download-data.selector.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/language/language.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/language/language.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/language/language.reducer.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/language/language.selector.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/role/role.effects.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-edition-new-basic/rds-comp-edition-new-basic.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-edition-new-basic/rds-comp-edition-new-basic.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features-list-new/rds-comp-features-list-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features-list-new/rds-comp-features-list-new.component.ts
  raaghu-mfe/projects/rds-page-edition/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-login/src/app/abp.config.ts
Labels: A B P

#853 Line chart is not rendering in mfe storybook
  raaghu-elements/src/rds-chart-line/src/lib/rds-chart-line.component.ts
Labels: bug

#865 Bugs fixes- #849, .#846, and other observed issues
  raaghu-elements/src/rds-table/src/lib/rds-table.component.html
  raaghu-elements/src/rds-table/src/lib/rds-table.component.ts
  raaghu-elements/src/root/styles-storybook.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/libs/themes/src/styles/nav-tab.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-pricing-table/pricing-table.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-pricing-table/rds-comp-pricing-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-pricing-table/rds-comp-pricing-table.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/stories/Introduction.stories.mdx
Labels: bug, ASP.net

#877 PR for bug #847
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
Labels: bug

#878 text template page data binding
  raaghu-mfe/projects/host/src/app/app.module.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/state-management/src/lib/app.interface.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/text-template/text-template.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/text-template/text-template.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/text-template/text-template.reducer.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/text-template/text-template.selector.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/user/user.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/user/user.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/user/user.reducer.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/user/user.selector.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-page-text-template/src/app/app.component.html
  raaghu-mfe/projects/rds-page-text-template/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-user/src/app/app.component.ts
Labels: A B P

#879 Bug fixed- #850 #852 #246 #806
  raaghu-elements/src/rds-radio-button/src/lib/rds-radio-button.component.html
  raaghu-elements/src/rds-radio-button/src/lib/rds-radio-button.component.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.html
  raaghu-mfe/projects/libs/themes/src/styles/dropdown.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
Labels: bug

#891 Host Admin UI bugs
  raaghu-elements/package.json
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.html
  raaghu-elements/src/rds-icon/src/lib/icons.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login-attempts/rds-comp-login-attempts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
Labels: bug

#905 Bug Fixed- #876, #888
  raaghu-elements/src/rds-banner/src/lib/rds-banner.component.ts
  raaghu-mfe/projects/libs/themes/src/styles/card.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-email/rds-comp-email.component.html
Labels: bug, ASP.net

#911 PR for bug #214, #805 and #894
  raaghu-mfe/projects/rds-components/src/app/rds-comp-organization-tree/rds-comp-organization-tree.component.html
  raaghu-mfe/projects/rds-page-edition/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-organization-unit/src/app/app.component.html
Labels: bug

#914 Bug Fixed- sidebar white space issue on dark mode
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.html
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
Labels: bug, Angular

#915 Bug fixed- #898 #895 #297 #281
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-settings/rds-comp-tenant-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basics/rds-comp-user-basics.component.html
  raaghu-mfe/projects/rds-page-organization-unit/src/app/app.component.html
Labels: bug

#917 Host Admin UI bugs
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/default.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-visual-settings/rds-comp-visual-settings.component.html
Labels: bug

#931 storybook build issue resolved
  raaghu-elements/src/rds-card/src/lib/card.stories.ts
  raaghu-elements/src/rds-price/src/lib/price.stories.ts
  raaghu-elements/src/rds-tags/src/lib/tags.stories.ts
  raaghu-elements/src/rds-team-member/src/lib/team-member.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-other-settings/other-settings.stories.ts
Labels: storybook

#919 committed changes for adding dummy profile picture to profile offcanvas
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/host/src/assets/profile-picture.png
Labels: bug

#924 Console error resolved
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.html
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.ts
  raaghu-mfe/gatsby/src/assets/data/elements.json
Labels: gatsby, ASP.net

#926 Development abp - Language page
  raaghu-mfe/projects/host/src/assets/appconfig.json
  raaghu-mfe/projects/libs/state-management/src/lib/state/language/language.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/language/language.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/language/language.selector.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-language-new/rds-comp-language-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-language-new/rds-comp-language-new.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-language-text-list/rds-comp-language-text-list.component.ts
  raaghu-mfe/projects/rds-components/webpack.config.js
  raaghu-mfe/projects/rds-page-language/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-login/src/app/abp.config.ts
Labels: A B P

#934 Fixed Host Admin UI bugs
  raaghu-mfe/projects/rds-components/src/app/rds-comp-email/rds-comp-email.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-invoice/rds-comp-invoice.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-language/rds-comp-new-language.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-other-settings/rds-comp-other-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-security/rds-comp-security.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-management/rds-comp-tenant-management.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-management/rds-comp-user-management.component.html
  raaghu-mfe/projects/rds-page-settings/src/app/app.component.html
Labels: bug

#935 PR for bug #903
  raaghu-mfe/projects/rds-components/src/app/rds-comp-cache/rds-comp-cache.component.html
Labels: bug

#943 Bug Fixes:#829,#851,#906,#928
  raaghu-elements/src/rds-button/src/lib/rds-button.component.ts
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.html
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.ts
  raaghu-mfe/gatsby/src/components/Sidebar.js
  raaghu-mfe/gatsby/src/pages/{markdownRemark.frontmatter__slug}.js
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.html
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.html
Labels: bug

#945 Bug Fixes- #941 #895
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basics/rds-comp-user-basics.component.html
Labels: bug

#946 Bug fixed #925
  raaghu-mfe/projects/rds-components/src/app/rds-comp-information/rds-comp-information.component.html
Labels: bug

#949 Gatsby undefined checking added
  raaghu-mfe/gatsby/src/components/Sidebar.js
Labels: bug

#957 UI bug fixed for PR no. #921, #950, #416
  raaghu-elements/src/rds-popover/src/lib/rds-popover.component.html
  raaghu-mfe/projects/libs/themes/src/styles/card.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
Labels: bug

#972 Bug Fixed : #964, #965 and 616
  raaghu-elements/src/rds-banner/src/lib/rds-banner.component.ts
  raaghu-elements/src/rds-checkbox/src/lib/rds-checkbox.component.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-linked-accounts/rds-comp-linked-accounts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-mysettings/rds-comp-mysettings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-delegations/rds-comp-user-delegations.component.html
  raaghu-mfe/projects/rds-page-webhooksubscription/src/app/app.component.html
Labels: bug

#981 Bugs Fixed: #909,#918,#929,#936---
  raaghu-elements/src/rds-button/src/lib/rds-button.component.ts
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.ts
  raaghu-mfe/gatsby/src/components/Sidebar.js
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/user/user.effects.ts
  raaghu-mfe/projects/libs/themes/src/styles/accessible.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/green.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-dynamic-entity-property/rds-comp-new-dynamic-entity-property.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-language/rds-comp-new-language.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-language/rds-comp-new-language.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-role/rds-comp-new-role.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-settings/rds-comp-tenant-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-webhook-subscription/rds-comp-webhook-subscription.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-webhook-subscription/rds-comp-webhook-subscription.component.ts
  raaghu-mfe/projects/rds-page-edition/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-language/src/app/app.component.html
  raaghu-mfe/projects/rds-page-language/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-login/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-settings/src/app/app.component.html
  raaghu-mfe/projects/rds-page-settings/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-user/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-webhooksubscription/src/app/app-routing.module.ts
  raaghu-mfe/projects/rds-page-webhooksubscription/src/app/app.component.html
  raaghu-mfe/projects/rds-page-webhooksubscription/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-webhooksubscription/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-webhooksubscription/src/app/webhooksubscription/webhooksubscription.component.html
  raaghu-mfe/projects/rds-page-webhooksubscription/src/app/webhooksubscription/webhooksubscription.component.scss
  raaghu-mfe/projects/rds-page-webhooksubscription/src/app/webhooksubscription/webhooksubscription.component.spec.ts
  raaghu-mfe/projects/rds-page-webhooksubscription/src/app/webhooksubscription/webhooksubscription.component.ts
Labels: bug

#980 Host admin Off canvas Remove scrollbar from My Settings
  raaghu-mfe/projects/rds-components/src/app/rds-comp-mysettings/rds-comp-mysettings.component.scss
Labels: bug

#987 gatsby first time loading issue resolved
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.html
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.ts
  raaghu-mfe/gatsby/src/components/Sidebar.js
Labels: bug

#993 Bug Fix: #953
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.scss
  raaghu-mfe/projects/libs/themes/src/styles/accessible.scss
  raaghu-mfe/projects/libs/themes/src/styles/blue.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/default.scss
  raaghu-mfe/projects/libs/themes/src/styles/green.scss
  raaghu-mfe/projects/libs/themes/src/styles/orange.scss
Labels: bug, ASP.net, Angular

#954 PR for bug #857
  raaghu-elements/src/rds-button/src/lib/button.stories.ts
  raaghu-elements/src/rds-button/src/lib/rds-button.component.ts
  raaghu-elements/src/rds-pagination/src/lib/rds-pagination.component.html
  raaghu-elements/src/rds-pagination/src/lib/rds-pagination.component.scss
  raaghu-elements/src/root/styles-storybook.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.ts
Labels: bug

#995 Bug Fixed: #983
  raaghu-elements/src/rds-dropdown/src/lib/rds-dropdown.component.html
  raaghu-mfe/projects/libs/shared/src/lib/user-auth.service.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.ts
  raaghu-mfe/projects/rds-page-login/src/app/app.component.ts
Labels: bug

#1011 Host admin Settings Dropdown should open below the field. & Host admin Dropdowns Arrow should be move upwards and downwards after opening or closing.
  raaghu-elements/src/rds-dropdownlist/src/lib/dropdownlist.stories.ts
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.html
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.scss
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-information/information.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-information/rds-comp-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-information/rds-comp-information.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-management/rds-comp-tenant-management.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-management/tenant-management.stories.ts
  raaghu-mfe/projects/rds-page-dynamic-property-management/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-settings/src/app/app.component.ts
Labels: bug

#1012 committed for bugs #901 #904 #990
  raaghu-elements/src/rds-button/src/lib/button.stories.ts
  raaghu-elements/src/rds-button/src/lib/rds-button.component.ts
  raaghu-elements/src/rds-icon/src/lib/icons.ts
  raaghu-elements/src/rds-select-list/src/lib/rds-select-list.component.html
  raaghu-elements/src/rds-select-list/src/lib/rds-select-list.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-cache/rds-comp-cache.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-notification/rds-comp-notification.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
Labels: bug

#1020 committed changes for users role was not getting added in data-table
  raaghu-elements/src/rds-button/src/lib/rds-button.component.ts
  raaghu-elements/src/rds-checkbox/src/lib/rds-checkbox.component.ts
  raaghu-elements/src/rds-select-list/src/lib/rds-select-list.component.ts
Labels: bug

#1022 Spinner is there on save button after opening the off canvas.#1008
  raaghu-elements/src/rds-button/src/lib/rds-button.component.html
  raaghu-elements/src/rds-button/src/lib/rds-button.component.ts
  raaghu-mfe/projects/libs/shared/src/lib/user-auth.service.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-mysettings/rds-comp-mysettings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-mysettings/rds-comp-mysettings.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.ts
  raaghu-mfe/projects/rds-components/src/models/profile.model.ts
  raaghu-mfe/projects/rds-page-login/src/app/app.component.ts
Labels: bug

#1023 sidenav issue fixed
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-mysettings/rds-comp-mysettings.component.ts
Labels: bug

#1024 Bug Fix: #985
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.html
Labels: bug, ASP.net, Angular

#1025 PR for bug #950, #1009 & #1010
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login-attempts/rds-comp-login-attempts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.ts
Labels: bug

#1029 Bug Fixes #1001 #1003 #1004
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login-attempts/rds-comp-login-attempts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.html
Labels: bug

#958 Development
  raaghu-mfe/.npmrc
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-visual-settings/rds-comp-visual-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-visual-settings/rds-comp-visual-settings.component.ts
  raaghu-mfe/projects/rds-page-visual-settings/src/app/app.component.ts
Labels: bug, ASP.net

#1035 Bug Fix: #803
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.html
Labels: bug, ASP.net, Angular

#1036 Host admin New tenant Edition dropdown issue.
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/tenant.information.stories.ts
  raaghu-mfe/projects/rds-page-tenant/src/app/app.component.ts
Labels: bug

#1037 Fixed Bugs: 986 and 1002
  raaghu-elements/src/rds-datepicker/src/lib/rds-datepicker.component.scss
  raaghu-elements/src/rds-nav-tab/src/lib/rds-nav-tab.component.scss
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.scss
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.html
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/themes/src/styles/card.scss
  raaghu-mfe/projects/libs/themes/src/styles/responsive.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login-attempts/rds-comp-login-attempts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.scss
Labels: bug

#1038 Development
  raaghu-elements/src/rds-card/src/lib/card.stories.ts
  raaghu-elements/src/rds-card/src/lib/rds-card.component.html
  raaghu-elements/src/rds-card/src/lib/rds-card.component.ts
  raaghu-mfe/angular.json
  raaghu-mfe/projects/host/src/index.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-plan-information/rds-comp-plan-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-subscription/rds-comp-subscription.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-subscription/rds-comp-subscription.component.scss
Labels: bug, ASP.net

#1039 PR for bug#1016 & #1026
  raaghu-elements/src/rds-button/src/lib/rds-button.component.ts
Labels: bug

#1042 bugs fixed: #947,#1032,#1008--------
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/shared/src/lib/user-auth.service.ts
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-delegations/rds-comp-user-delegations.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-delegations/rds-comp-user-delegations.component.ts
Labels: bug

#1043 committed for bugs #994 #990 and #1015
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-alert-popup/rds-comp-alert-popup.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-language/rds-comp-new-language.component.html
Labels: bug

#1044 committed changes for settings page save funtionality
  raaghu-mfe/projects/rds-components/src/app/rds-comp-email/rds-comp-email.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-email/rds-comp-email.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-invoice/rds-comp-invoice.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-invoice/rds-comp-invoice.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-other-settings/rds-comp-other-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-other-settings/rds-comp-other-settings.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-security/rds-comp-security.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-security/rds-comp-security.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-management/rds-comp-tenant-management.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-management/rds-comp-tenant-management.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-management/rds-comp-user-management.component.ts
  raaghu-mfe/projects/rds-page-settings/src/app/app.component.html
  raaghu-mfe/projects/rds-page-settings/src/app/app.component.ts
Labels: bug

#1045 Host admin>>Left navigation menu>>Remove tooltip from tenant, edition and dashboard.
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.html
Labels: bug

#1053 login page loading issue.
  raaghu-mfe/projects/rds-components/src/app/rds-comp-subscription/rds-comp-subscription.component.html
  raaghu-mfe/projects/rds-page-login/src/app/app.component.ts
Labels: bug, Angular

#1048 Host admin New role Spacing should be there between heading and search box
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-dynamic-entity-property/rds-comp-new-dynamic-entity-property.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.html
Labels: bug

#1049 Fixes: Login screen background color change And Bug. No. #890
  raaghu-elements/src/rds-chart-bool/src/lib/chart-icon.ts
  raaghu-mfe/projects/rds-page-login/src/app/app.component.html
  raaghu-mfe/projects/rds-page-login/src/app/app.component.scss
Labels: bug, ASP.net, Angular

#1051 Dropdowns and arrow alignment
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.html
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.scss
Labels: bug

#1055 PR for bug #1018
  raaghu-mfe/projects/host/src/assets/i18n/af-NA.json
  raaghu-mfe/projects/host/src/assets/i18n/am-ET.json
Labels: bug

#1059 Host admin Login Change alert message position to top
  raaghu-mfe/projects/rds-components/src/app/rds-comp-alert/rds-comp-alert.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-alert/rds-comp-alert.component.ts
  raaghu-mfe/projects/rds-page-login/src/app/app.component.ts
Labels: bug

#1060 committed for bugs #901 and #1006
  raaghu-elements/src/rds-icon/src/lib/flag-icons.ts
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/libs/themes/src/styles/default.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-notification/rds-comp-notification.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-notification/rds-comp-notification.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-notification/rds-comp-notification.component.ts
Labels: bug

#1062 Dropdown in settings page
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-management/rds-comp-tenant-management.component.html
  raaghu-mfe/projects/rds-page-settings/src/app/app.component.html
  raaghu-mfe/projects/rds-page-settings/src/app/app.component.ts
Labels: bug

#1063 Bug Fix:- #664
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.ts
  raaghu-elements/src/root/styles-storybook.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/tags.scss
Labels: bug, ASP.net, Angular

#1065 Bugs fixed: #928,#1047
  raaghu-mfe/projects/host/src/app/app.module.ts
  raaghu-mfe/projects/libs/state-management/src/lib/app.interface.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/dynamic-entity/dynamic-entity.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/dynamic-entity/dynamic-entity.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/dynamic-entity/dynamic-entity.reducer.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/dynamic-property-management/dynamic-property.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/dynamic-property-management/dynamic-property.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/dynamic-property-management/dynamic-property.reducer.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/dynamic-property-management/dynamic-property.selector.ts
  raaghu-mfe/projects/libs/state-management/src/public-api.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-enity-properties/rds-comp-dynamic-enity-properties.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-information/rds-comp-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-dynamic-entity-property/rds-comp-new-dynamic-entity-property.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-dynamic-entity-property/rds-comp-new-dynamic-entity-property.component.ts
  raaghu-mfe/projects/rds-page-dynamic-property-management/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-dynamic-property-management/src/app/app.module.ts
Labels: bug

#1071 Host admin Audit logs Alignment issues
  raaghu-elements/src/rds-input/src/lib/rds-input.component.html
Labels: bug

#1079 committed for sidenav issue for storybook
  raaghu-elements/src/root/styles-storybook.scss
Labels: bug

#1081 Host admin Asterisk signs should be there for all mandatory fields
  raaghu-elements/src/rds-input/src/lib/rds-input.component.html
Labels: bug

#1083 resolved bugs in dropdownlist
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.html
Labels: bug

#1085 Bug Fixed:#1066
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-enity-properties/rds-comp-dynamic-enity-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-enity-properties/rds-comp-dynamic-enity-properties.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-dynamic-entity-property/rds-comp-new-dynamic-entity-property.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-dynamic-entity-property/rds-comp-new-dynamic-entity-property.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
  raaghu-mfe/projects/rds-page-tenant/src/app/app.component.ts
Labels: bug

#1096 storybook build issue resolved.
  raaghu-mfe/projects/stories/Introduction.stories.mdx
Labels: bug, storybook

#1088 PR for bug #1069
  raaghu-elements/src/rds-collapse/src/lib/rds-collapse.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.ts
Labels: bug

#1102 Host admin Off canvas Spacing issues throughout the application
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-settings/rds-comp-tenant-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.html
Labels: bug

#1104 Bugs Fixed:#940,#1095
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-settings/rds-comp-tenant-settings.component.html
  raaghu-mfe/projects/rds-page-role/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-tenant/src/app/app.component.ts
Labels: bug

#1106 committed for alert issue for role , user
  raaghu-mfe/projects/libs/state-management/src/lib/state/role/role.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/user/user.effects.ts
Labels: bug

#1103 Development
  raaghu-elements/src/rds-checkbox/src/lib/rds-checkbox.component.scss
  raaghu-mfe/angular.json
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
Labels: bug, ASP.net, Angular

#1118 Bugs Fixed:#1092,#851-------------------
  raaghu-elements/src/rds-button/src/lib/rds-button.component.ts
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.html
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/shared/src/lib/alert.service.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-visual-settings/rds-comp-visual-settings.component.ts
Labels: bug

#1120 committed for login attempts page
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login-attempts/rds-comp-login-attempts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login-attempts/rds-comp-login-attempts.component.ts
Labels: bug

#1121 PR for bug #857 & #1091
  raaghu-mfe/projects/rds-components/src/app/rds-comp-information/rds-comp-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.ts
  raaghu-mfe/projects/rds-page-maintenance/src/app/app.component.html
  raaghu-mfe/projects/rds-page-maintenance/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-maintenance/src/app/maintenance/maintenance.component.html
Labels: bug

#1124 Language dropdown binding and arrow issue fixed
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
Labels: bug

#1126 committed changes for login as tenant functionality - bug - #996
  raaghu-mfe/projects/host/src/index.html
  raaghu-mfe/projects/libs/shared/src/lib/XmlHttpRequestHelper.ts
  raaghu-mfe/projects/libs/shared/src/lib/user-auth.service.ts
  raaghu-mfe/projects/libs/state-management/src/lib/app.interface.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/tenant/tenant.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/tenant/tenant.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/tenant/tenant.reducer.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/tenant/tenant.selector.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.ts
  raaghu-mfe/projects/rds-page-login/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-tenant/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-tenant/src/app/app.module.ts
Labels: bug

#1132 Bugs Fixed:1067
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-notification-settings/notification-settings.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-notification-settings/rds-comp-notification-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-notification-settings/rds-comp-notification-settings.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-open-position/open-position.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-delegations/rds-comp-user-delegations.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-delegations/rds-comp-user-delegations.component.ts
  raaghu-mfe/projects/rds-page-tenant/src/app/app.component.ts
Labels: bug

#1133 committed changes for changing url for login as tenant functionality
  raaghu-mfe/projects/rds-page-tenant/src/app/app.component.ts
Labels: bug

#1125 PR for bug #1016
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-information/rds-comp-information.component.ts
Labels: bug

#1140 profile picture functionality
  raaghu-elements/src/rds-avatar/src/lib/rds-avatar.component.html
  raaghu-elements/src/rds-avatar/src/lib/rds-avatar.component.ts
  raaghu-mfe/projects/host/src/app/app.module.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/state-management/src/lib/app.interface.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/mysettings/mysettings.action.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/profile-settings/profile-settings.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/profile-settings/profile-settings.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/profile-settings/profile-settings.models.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/profile-settings/profile-settings.reducers.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/profile-settings/profile-settings.selectors.ts
  raaghu-mfe/projects/rds-components/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
  raaghu-mfe/projects/rds-page-tenant/src/app/app.component.ts
Labels: enhancement, typescript, ASP.net, UI Design

#1142 PR for language dropdown issue
  raaghu-elements/src/rds-alert/src/lib/alert.stories.ts
  raaghu-elements/src/rds-alert/src/lib/rds-alert.component.scss
  raaghu-elements/src/rds-alert/src/lib/rds-alert.component.ts
  raaghu-elements/src/rds-banner/src/lib/banner.stories.ts
  raaghu-elements/src/rds-banner/src/lib/rds-banner.component.ts
  raaghu-elements/src/rds-dropdownlist/src/lib/dropdownlist.stories.ts
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.html
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.scss
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.html
  raaghu-mfe/projects/libs/shared/src/lib/alert.service.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/tenant/tenant.effects.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-alert/rds-comp-alert.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-alert/rds-comp-alert.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-page-role/src/app/app.component.ts
Labels: enhancement

#1144 committed for dropdown border Issue
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-security/rds-comp-security.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-management/rds-comp-tenant-management.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-management/rds-comp-user-management.component.html
Labels: bug

#1155 Development
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-mysettings/rds-comp-mysettings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-dynamic-entity-property/rds-comp-new-dynamic-entity-property.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-dynamic-entity-property/rds-comp-new-dynamic-entity-property.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-visual-settings/rds-comp-visual-settings.component.html
  raaghu-mfe/projects/rds-page-dynamic-property-management/src/app/app.component.ts
Labels: bug, ASP.net

#1159 committed for bugs #1146 #1152
  raaghu-elements/src/rds-avatar/src/lib/rds-avatar.component.html
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
Labels: bug

#1160 PR for bug #1149
  raaghu-elements/src/rds-alert/src/lib/rds-alert.component.html
  raaghu-elements/src/rds-alert/src/lib/rds-alert.component.scss
  raaghu-elements/src/rds-alert/src/lib/rds-alert.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-role-list/rds-comp-role-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.ts
  raaghu-mfe/projects/rds-page-dynamic-property-management/src/app/app.component.html
  raaghu-mfe/projects/rds-page-dynamic-property-management/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-dynamic-property-management/src/app/app.module.ts
Labels: bug

#1164 committed for bugs #1161 and #1163
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-alert-popup/rds-comp-alert-popup.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basics/rds-comp-user-basics.component.html
Labels: bug

#1168 Host admin>>Android>>Chrome>>Left navigation issues.#1166
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/shared/src/lib/shared.service.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
Labels: bug

#1167 PR for localize all text in dutch language
  raaghu-mfe/projects/host/src/assets/i18n/nl.json
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-email/rds-comp-email.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-linked-accounts/rds-comp-linked-accounts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login-attempts/rds-comp-login-attempts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-mysettings/rds-comp-mysettings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-language/rds-comp-new-language.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-security/rds-comp-security.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions-new/rds-comp-user-permissions-new.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-visual-settings/rds-comp-visual-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-visual-settings/rds-comp-visual-settings.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-webhook-subscription/rds-comp-webhook-subscription.component.html
  raaghu-mfe/projects/rds-page-language/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-role/src/app/app.component.ts
Labels: bug

#1169 Charts updated - Same charts with different colors for theme selection
  raaghu-elements/src/rds-chart-area/src/lib/rds-chart-area.component.ts
  raaghu-elements/src/rds-chart-bar-horizontal/src/lib/rds-chart-bar-horizontal.component.ts
  raaghu-elements/src/rds-chart-bool/src/lib/rds-chart-bool.component.ts
  raaghu-elements/src/rds-chart-bubble/src/lib/rds-chart-bubble.component.ts
  raaghu-elements/src/rds-chart-doughnut/src/lib/rds-chart-doughnut.component.ts
  raaghu-elements/src/rds-chart-line/src/lib/rds-chart-line.component.ts
  raaghu-elements/src/rds-chart-mixed/src/lib/rds-chart-mixed.component.ts
  raaghu-elements/src/rds-chart-pie/src/lib/rds-chart-pie.component.ts
  raaghu-elements/src/rds-chart-polar-area/src/lib/rds-chart-polar-area.component.ts
  raaghu-elements/src/rds-chart-radar/src/lib/rds-chart-radar.component.ts
  raaghu-elements/src/rds-chart-scatter/src/lib/rds-chart-scatter.component.ts
  raaghu-elements/src/rds-chart-stacked/src/lib/rds-chart-stacked.component.ts
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.ts
Labels: bug

#1172 committed for bugs #1163 and #1157
  raaghu-elements/src/rds-accordion/src/lib/accordion-item/accordion-item.component.html
  raaghu-elements/src/rds-toasts/src/lib/rds-toasts.component.html
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-notification-settings/rds-comp-notification-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-notification/rds-comp-notification.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-notification/rds-comp-notification.component.ts
Labels: bug

#1174 Host admin>>Users>>Filter by permission is not working.
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.ts
  raaghu-mfe/projects/rds-page-user/src/app/app.component.ts
Labels: bug, ASP.net

#1178 committed for bugs #1151 and #1171
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.ts
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables.scss
  raaghu-mfe/projects/libs/themes/src/styles/pagination.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
Labels: bug
