Repository Wai-Technologies/raaghu-angular, pull requests merged in 2023-02, with the labels that each got.

#1553 UI changes in ANZ
  raaghu-mfe/projects/rds-page-audit-logs/src/app/app.component.html
  raaghu-mfe/projects/rds-page-edition/src/app/app.component.html
Labels: bug, ASP.net, Angular

#1554 committed changes for back to account button issue
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
Labels: bug, ASP.net, Angular

#1557 Remove meta tag for mobile view
  raaghu-mfe/projects/host/src/index.html
Labels: bug, ASP.net, Angular

#1560 UI change in StageUI
  raaghu-elements/src/rds-pagination/src/lib/rds-pagination.component.html
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-alert/rds-comp-alert.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-information/rds-comp-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-page-dynamic-property-management/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-subscription/src/app/app.component.html
Labels: bug, ASP.net, Angular

#1561 Element enhancement and forgot password page enhancement
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.html
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.ts
  raaghu-elements/src/rds-input/src/lib/rds-input.component.html
  raaghu-elements/src/rds-stepper/src/lib/rds-stepper.component.scss
  raaghu-elements/src/rds-stepper/src/lib/rds-stepper.stories.ts
  raaghu-elements/src/rds-team-member/src/lib/rds-team-member.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-forgot-password/rds-comp-forgot-password.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-forgot-password/rds-comp-forgot-password.component.ts
  raaghu-mfe/projects/rds-page-forgot-password/src/app/app.component.html
Labels: bug, ASP.net, Angular

#1562 Data table updation changes
  raaghu-elements/src/rds-radio-button/src/lib/rds-radio-button.component.html
  raaghu-elements/src/rds-radio-button/src/lib/rds-radio-button.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/data-table.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.ts
Labels: enhancement, ASP.net, Angular

#1565 committed for user page issue
  raaghu-elements/src/rds-pagination/src/lib/rds-pagination.component.html
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.html
  raaghu-mfe/projects/host/src/assets/appconfig.json
  raaghu-mfe/projects/libs/state-management/src/lib/state/user/user.actions.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/user/user.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/user/user.reducer.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features-list-new/rds-comp-features-list-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-properties/rds-comp-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions-new/rds-comp-user-permission-new.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions-new/rds-comp-user-permissions-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions-new/rds-comp-user-permissions-new.component.ts
  raaghu-mfe/projects/rds-page-api-resources/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-identity-resources/src/app/app.component.html
  raaghu-mfe/projects/rds-page-identity-resources/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-language-text/webpack.config.js
  raaghu-mfe/projects/rds-page-login/src/app/abp.config.ts
  raaghu-mfe/projects/rds-page-tenant/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-user/src/app/app.component.html
  raaghu-mfe/projects/rds-page-user/src/app/app.component.ts
Labels: ABP

#1588 Create expandable datatable in datatble component
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/data-table.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.scss
Labels: enhancement, Angular
