Repository Wai-Technologies/raaghu-angular, pull requests merged in 2023-01, with the labels that each got.

#1374 Storybook element UI issues FIXES
  raaghu-elements/src/rds-app-details/src/lib/rds-app-details.component.html
  raaghu-elements/src/rds-badge/src/lib/rds-badge.component.ts
  raaghu-elements/src/rds-banner/src/lib/rds-banner.component.html
  raaghu-elements/src/rds-button/src/lib/button.stories.ts
  raaghu-elements/src/rds-button/src/lib/rds-button.component.ts
  raaghu-elements/src/rds-checkbox-groups/src/lib/rds-checkbox-groups.component.html
  raaghu-elements/src/rds-checkbox-parent-child/src/lib/rds-checkbox-parent-child.component.html
  raaghu-elements/src/rds-dropdown/src/lib/rds-dropdown.component.html
  raaghu-elements/src/rds-fab-menu/src/lib/fabmenu.stories.ts
  raaghu-elements/src/rds-fab-menu/src/lib/rds-fab-menu.component.html
  raaghu-elements/src/rds-icon/src/lib/icons.ts
  raaghu-elements/src/rds-pagination/src/lib/pagination.stories.ts
  raaghu-elements/src/rds-popular-pages/src/lib/rds-popular-pages.component.html
  raaghu-elements/src/rds-scrollspy/src/lib/rds-scrollspy.component.html
  raaghu-elements/src/rds-scrollspy/src/lib/scrollspy.stories.ts
  raaghu-elements/src/rds-search-input/src/lib/rds-search-input.component.scss
  raaghu-elements/src/rds-stepper/src/lib/rds-stepper.component.html
  raaghu-elements/src/rds-stepper/src/lib/rds-stepper.component.scss
  raaghu-elements/src/root/styles-storybook.scss
  raaghu-mfe/projects/libs/themes/src/styles/carousel.scss
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables-light.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
Labels: bug, ASP.net, Angular

#1383 Storybook - Functional issues for elements
  raaghu-elements/src/rds-avatar/src/lib/avatar.stories.ts
  raaghu-elements/src/rds-avatar/src/lib/rds-avatar.component.html
  raaghu-elements/src/rds-avatar/src/lib/rds-avatar.component.ts
  raaghu-elements/src/rds-checkbox-parent-child/src/lib/checkbox-parent-child.stories.ts
  raaghu-elements/src/rds-checkbox/src/lib/checkbox.stories.ts
  raaghu-elements/src/rds-checkbox/src/lib/rds-checkbox.component.ts
  raaghu-elements/src/rds-color-picker/src/lib/color-picker.stories.ts
  raaghu-elements/src/rds-feature-list/src/lib/rds-feature-list.component.html
  raaghu-elements/src/rds-offcanvas/src/lib/offcanvas.stories.ts
  raaghu-elements/src/rds-offcanvas/src/lib/rds-offcanvas.component.html
  raaghu-elements/src/rds-scrollspy/src/lib/rds-scrollspy.component.html
  raaghu-elements/src/rds-scrollspy/src/lib/rds-scrollspy.module.ts
  raaghu-mfe/.storybook/main.js
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-claims/rds-comp-claims.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-basics/rds-comp-client-basics.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-basics/rds-comp-client-basics/rds-comp-client-basics-shimmer/rds-comp-client-basics-shimmer.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-client-basics/rds-comp-client-basics/rds-comp-client-basics.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-contact-information/rds-comp-contact-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-email/rds-comp-email.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-hierarchy/rds-comp-hierarchy.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-role/rds-comp-new-role.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-notification-settings/rds-comp-notification-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-other-settings/rds-comp-other-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-security/rds-comp-security.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-basic-profile-right/rds-comp-tenant-basic-profile-right.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-features/rds-comp-tenant-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-management/rds-comp-tenant-management.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-settings/rds-comp-tenant-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basic-profile-right/rds-comp-user-basic-profile-right.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basics/rds-comp-user-basics.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-management/rds-comp-user-management.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions-new/rds-comp-user-permissions-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-table/rds-comp-user-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-visual-settings/rds-comp-visual-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-webhook-subscription/rds-comp-webhook-subscription.component.html
  raaghu-mfe/projects/rds-page-audit-logs/src/app/app.component.html
Labels: storybook, ASP.net, Angular

#1384 UI Fixes in storybook Elements
  raaghu-elements/assets/benefit_type1.png
  raaghu-elements/src/rds-avatar/src/lib/rds-avatar.component.html
  raaghu-elements/src/rds-avatar/src/lib/rds-avatar.component.ts
  raaghu-elements/src/rds-badge/src/lib/badge.stories.ts
  raaghu-elements/src/rds-badge/src/lib/rds-badge.component.scss
  raaghu-elements/src/rds-benefit/src/lib/rds-benefit.component.html
  raaghu-elements/src/rds-big-number-widget/src/lib/rds-big-number.component.html
  raaghu-elements/src/rds-button/src/lib/rds-button.component.html
  raaghu-elements/src/rds-dropdown/src/lib/dropdown.stories.ts
  raaghu-elements/src/rds-dropdown/src/lib/rds-dropdown.component.html
  raaghu-elements/src/rds-dropdown/src/lib/rds-dropdown.component.ts
  raaghu-elements/src/rds-fab-menu/src/lib/fabmenu.stories.ts
  raaghu-elements/src/rds-fab-menu/src/lib/rds-fab-menu.component.html
  raaghu-elements/src/rds-fab-menu/src/lib/rds-fab-menu.component.scss
  raaghu-elements/src/rds-fab-menu/src/lib/rds-fab-menu.component.ts
  raaghu-elements/src/rds-feed/src/lib/rds-feed.component.html
  raaghu-elements/src/root/styles-storybook.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
Labels: bug, ASP.net, Angular

#1387 Removed error in button elements
  raaghu-elements/src/rds-button/src/lib/rds-button.component.ts
  raaghu-elements/src/rds-scrollspy/src/lib/rds-scrollspy.component.html
  raaghu-elements/src/rds-website-metric/src/lib/rds-website-metric.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-webhook-subscription/rds-comp-webhook-subscription.component.html
Labels: bug, ASP.net, Angular

#1393 changes in tenant alert notification and removing login button
  raaghu-mfe/projects/host/src/app/app.routes.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/tenant/tenant.effects.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-integration/integration.stories.ts
  raaghu-mfe/projects/rds-page-dashboard/src/app/dashboard/dashboard.component.html
  raaghu-mfe/projects/rds-page-edition/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-tenant/src/app/app.component.html
  raaghu-mfe/projects/rds-page-tenant/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-tenant/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-tenant/webpack.config.js
Labels: bug, ASP.net, Angular

#1402 Resolving stageui issues
  raaghu-elements/src/rds-app-details/src/lib/rds-app-details.component.html
  raaghu-elements/src/rds-button/src/lib/button.stories.ts
  raaghu-elements/src/rds-button/src/lib/rds-button.component.html
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.html
  raaghu-elements/src/rds-icon/src/lib/icons.ts
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.html
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.scss
  raaghu-elements/src/rds-size/src/lib/rds-size.component.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-apply-for-position/rds-comp-apply-for-position.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/auditlog.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-audit-logs/rds-comp-audit-logs.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-card-detail-list/carddetaillist.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-contact-information/rds-comp-contact-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-contact-us/rds-comp-contact-us.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-delivery-method/rds-comp-delivery-method.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-enity-properties/rds-comp-dynamic-enity-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-edit-language-text/rds-comp-edit-language-text.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-email-settings/rds-comp-email-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-dynamic-entity-property/rds-comp-new-dynamic-entity-property.component.html
  raaghu-mfe/projects/rds-page-audit-logs/src/app/app.component.html
  raaghu-mfe/projects/rds-page-maintenance/src/app/app.component.html
  raaghu-mfe/projects/rds-page-settings/src/app/app.component.html
Labels: bug, ASP.net, Angular

#1403 changes on alert notification, dynamic-properties title, user-permiss…
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-enity-properties/rds-comp-dynamic-enity-properties.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.html
  raaghu-mfe/projects/rds-page-role/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-tenant/src/app/app.component.html
Labels: bug, ASP.net, Angular

#1404 Bug Fixes- #13478, #1377, #1286
  raaghu-elements/src/rds-big-number-widget/src/lib/rds-big-number.component.html
  raaghu-elements/src/root/styles-storybook.scss
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.ts
Labels: bug, ASP.net, Angular

#1405 Updating icons & adding missing once
  raaghu-elements/src/rds-icon/src/lib/icons.ts
Labels: bug, ASP.net, Angular

#1407 Development abp > Roles Page
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.html
  raaghu-mfe/projects/libs/rds-cookieconsent/src/lib/service/cookieconsent.service.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/role/role.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/user/user.actions.ts
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/libs/themes/src/styles/offcanvas.scss
  raaghu-mfe/projects/rds-components/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-basic-resource/rds-comp-basic-resource.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-claim-type-role/rds-comp-claim-type-role.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-claim-type-role/rds-comp-claim-type-role.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-claim-type-role/rds-comp-claims-type-role.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-alert-popup/rds-comp-alert-popup.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-role/rds-comp-new-role.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-role/rds-comp-new-role.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-organization-tree/rds-comp-organization-tree.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-organization-tree/rds-comp-organization-tree.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-organization-tree/rds-comp-organization-tree.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.ts
  raaghu-mfe/projects/rds-components/webpack.config.js
  raaghu-mfe/projects/rds-page-role/src/app/app.component.html
  raaghu-mfe/projects/rds-page-role/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-role/src/app/app.module.ts
Labels: bug, A B P

#1415 committed changes for ui of storybook components faq - new role
  raaghu-mfe/projects/rds-components/src/app/rds-comp-faq/rds-comp-faq.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/edition.list.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-integration/rds-comp-integration.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-linked-accounts/rds-comp-linked-accounts.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login-attempts/login-attempts.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-marketing-website-newsletter/marketingwebsitenewsletter.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-marketing-website-newsletter/rds-comp-marketing-website-newsletter.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-marketing-website-newsletter/rds-comp-marketing-website-newsletter.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-member-activity/rds-comp-member-activity.component.html
Labels: bug, ASP.net, Angular

#1421 Commit for icon border and animation changes
  raaghu-elements/src/rds-button/src/lib/rds-button.component.html
  raaghu-elements/src/rds-input/src/lib/rds-input.component.html
  raaghu-mfe/projects/libs/themes/src/styles/dropdown.scss
Labels: bug, ASP.net, Angular

#1422 PR for demo ui structure changes
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
Labels: bug, ASP.net, Angular

#1423 committed changes for teams to user-claims component for storybook issue
  raaghu-mfe/.storybook/assets/DarkThemeNew.png
  raaghu-mfe/.storybook/assets/LightThemeNew.png
  raaghu-mfe/.storybook/assets/accessibleThemeNew.png
  raaghu-mfe/projects/rds-components/src/app/rds-comp-marketing-website-newsletter/rds-comp-marketing-website-newsletter.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-basic-profile-right/rds-comp-tenant-basic-profile-right.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-basic-profile-right/rds-comp-tenant-basic-profile-right.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-basic-profile-right/rds-comp-tenant-basic-profile-right.component.spec.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-basic-profile-right/rds-comp-tenant-basic-profile-right.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-basic-profile-right/rds-comp-tenant-basic-profile-right.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-basic-profile-right/tenant-basic-profile-right.md
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-basic-profile-right/tenant.information.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-features/rds-comp-tenant-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-features/rds-comp-tenant-features.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-features/rds-comp-tenant-features.component.spec.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-features/rds-comp-tenant-features.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-features/rds-comp-tenant-features.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-features/tenant-features.md
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-features/tenant.features.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/tenant.information.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basic-profile-right/rds-comp-user-basic-profile-right.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basic-profile-right/rds-comp-user-basic-profile-right.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basic-profile-right/rds-comp-user-basic-profile-right.component.spec.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basic-profile-right/rds-comp-user-basic-profile-right.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basic-profile-right/rds-comp-user-basic-profile-right.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basic-profile-right/user-basic-profile-right.md
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basic-profile-right/user-basic-profile-right.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-delegations/rds-comp-user-delegations.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions-new/rds-comp-user-permissions-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions-new/rds-comp-user-permissions-new.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions-new/rds-comp-user-permissions-new.component.spec.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions-new/rds-comp-user-permissions-new.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions-new/rds-comp-user-permissions-new.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions-new/user-permission-new.md
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions-new/user-permissions-new.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-table/rds-comp-user-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-table/rds-comp-user-table.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-table/rds-comp-user-table.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-table/rds-user-table.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-table/user-table.md
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-table/user-table.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-visual-settings/visual-settings.stories.ts
  raaghu-mfe/projects/rds-page-user/src/app/app.component.html
Labels: bug, ASP.net

#1432 fixed iphones content not displaying bugs
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
Labels: bug, ASP.net

#1433 storybook functional issue.
  raaghu-elements/src/rds-address-detail/src/lib/rds-address-detail.component.html
  raaghu-elements/src/rds-address-detail/src/lib/rds-address-detail.component.ts
  raaghu-mfe/.storybook/assets/edit-pic.png
  raaghu-mfe/.storybook/assets/page_not.svg
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.html
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-app-details/app-details-comp.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-open-position/open-position.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-open-position/rds-comp-open-position.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-open-position/rds-comp-open-position.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-other-settings/other-settings.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-page-not-found/rds-comp-page-not-found.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-plan-information/plan-information.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-pricing-table/pricing-table.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-pricing-table/rds-comp-pricing-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-pricing-table/rds-comp-pricing-table.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-pricing-table/rds-comp-pricing-table.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-product-list/rds-comp-product-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-shipping-address/rds-comp-shipping-address.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-shipping-address/rds-comp-shipping-address.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-subscription/rds-comp-subscription.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-subscription/subscription.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-management/rds-comp-user-management.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-webhook-subscription/rds-comp-webhook-subscription.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-website-log/rds-comp-website-log.component.html
Labels: storybook

#1436 Development abp Edition Page
  raaghu-mfe/projects/host/src/app/app.module.ts
  raaghu-mfe/projects/host/src/assets/appconfig.json
  raaghu-mfe/projects/libs/state-management/src/lib/state/edition/edition.action.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/edition/edition.effects.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/edition/edition.reducer.ts
  raaghu-mfe/projects/libs/state-management/src/lib/state/edition/edition.selector.ts
  raaghu-mfe/projects/libs/themes/src/styles/colorvariables-light.scss
  raaghu-mfe/projects/libs/themes/src/styles/custom.scss
  raaghu-mfe/projects/libs/themes/src/styles/default.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-edition-new-basic/rds-comp-edition-new-basic.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-edition-new-basic/rds-comp-edition-new-basic.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-edition-new-basic/rds-comp-edition-new-basic.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-edition-new-features/rds-comp-edition-new-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-edition-new-features/rds-comp-edition-new-features.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-edition-new-features/rds-comp-edition-new-features.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features-list-new/rds-comp-features-list-new.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features-list-new/rds-comp-features-list-new.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features-list-new/rds-comp-features-list-new.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features-list-new/rds-comp-features-list-new.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-permission-tree/rds-comp-permission-tree.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-features/rds-comp-tenant-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list-new/rds-comp-tenant-list-new.component.ts
  raaghu-mfe/projects/rds-page-edition/src/app/app.component.html
  raaghu-mfe/projects/rds-page-edition/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-edition/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-role/src/app/app.component.ts
Labels: bug, ABP

#1437 dynamic property fixes
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-review-category/rds-comp-review-category.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-review-category/review-category.stories.ts
Labels: bug, ASP.net, Angular

#1444 committed changes for storybook page issue
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-product-list/rds-comp-product-list.component.ts
  raaghu-mfe/projects/rds-page-audit-logs/src/app/app.component.html
  raaghu-mfe/projects/rds-page-audit-logs/src/app/auditlog.stories.ts
  raaghu-mfe/projects/rds-page-cart/src/app/cart.stories.ts
  raaghu-mfe/projects/rds-page-dashboard/src/app/dashboard/dashboard.stories.ts
  raaghu-mfe/projects/rds-page-edition/src/app/Edition.stories.ts
  raaghu-mfe/projects/rds-page-edition/src/app/app.component.html
  raaghu-mfe/projects/rds-page-frequently-asked-questions/src/app/app.component.html
  raaghu-mfe/projects/rds-page-frequently-asked-questions/src/app/faq.stories.ts
  raaghu-mfe/projects/rds-page-infinite-product-list/src/app/app.component.html
  raaghu-mfe/projects/rds-page-infinite-product-list/src/app/infinite-product-list.stories.ts
Labels: bug, ASP.net, Angular

#1446 fixed Iphones spacing bugs
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.html
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.scss
Labels: bug, ASP.net

#1447 chart element issue.
  raaghu-elements/src/rds-chart-area/src/lib/chart-area.stories.ts
  raaghu-elements/src/rds-chart-bool/src/lib/chart-bool.stories.ts
  raaghu-elements/src/rds-chart-bubble/src/lib/chart-bubble.stories.ts
  raaghu-elements/src/rds-chart-line/src/lib/chart-line.stories.ts
  raaghu-elements/src/rds-chart-mixed/src/lib/chart-mixed.stories.ts
  raaghu-elements/src/rds-review-category/src/lib/rds-review-category.component.html
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.scss
Labels: bug, storybook, Angular

#1453 Update theme version 0.0.7
  raaghu-mfe/package.json
Labels: Angular

#1456 Changes and enhancements in StageUI
  raaghu-mfe/.storybook/assets/Raaghu-logo-mfe-white.png
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-enity-properties/rds-comp-dynamic-enity-properties.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-enity-properties/rds-comp-dynamic-enity-properties.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-dynamic-properties/rds-comp-dynamic-properties.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-dynamic-entity-property/rds-comp-new-dynamic-entity-property.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-dynamic-entity-property/rds-comp-new-dynamic-entity-property.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-plan-information/rds-comp-plan-information.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.scss
  raaghu-mfe/projects/rds-page-dynamic-property-management/src/app/app.component.html
  raaghu-mfe/projects/rds-page-dynamic-property-management/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-organization-unit/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-role/src/app/app.component.html
  raaghu-mfe/projects/rds-page-role/src/app/app.component.ts
Labels: bug, ASP.net, Angular

#1457 storybook page changes
  raaghu-elements/src/rds-file-uploader/src/lib/rds-file-uploader.component.html
  raaghu-elements/src/rds-search-input/src/lib/rds-search-input.module.ts
  raaghu-mfe/.storybook/assets/carrers-page-illustration.svg
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basics/rds-comp-user-basics.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/user-permissions.stories.ts
  raaghu-mfe/projects/rds-page-edition/src/app/Edition.stories.ts
  raaghu-mfe/projects/rds-page-page-not-found/src/app/page-not-found.stories.ts
  raaghu-mfe/projects/rds-page-role/src/app/app.module.ts
  raaghu-mfe/projects/rds-page-role/src/app/role.stories.ts
  raaghu-mfe/projects/rds-page-securitylog/src/app/Security-log.stories.ts
  raaghu-mfe/projects/rds-page-tenant/src/app/tenant.stories.ts
  raaghu-mfe/projects/rds-page-text-template/src/app/text-template.stories.ts
  raaghu-mfe/projects/rds-page-under-construction/src/app/app.component.html
  raaghu-mfe/projects/rds-page-under-construction/src/app/under-construction.stories.ts
  raaghu-mfe/projects/rds-page-user/src/app/user.stories.ts
Labels: bug, storybook

#1458 committed changes for storybook pages issue
  raaghu-mfe/projects/rds-page-client/src/app/client.stories.ts
  raaghu-mfe/projects/rds-page-edition/src/app/Edition.stories.ts
  raaghu-mfe/projects/rds-page-infinite-product-list/src/app/app.component.html
  raaghu-mfe/projects/rds-page-infinite-product-list/src/app/infinite-product-list.stories.ts
  raaghu-mfe/projects/rds-page-language-text/src/app/language-text.stories.ts
  raaghu-mfe/projects/rds-page-language/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-language/src/app/language.stories.ts
  raaghu-mfe/projects/rds-page-maintenance/src/app/maintenance.stories.ts
  raaghu-mfe/projects/rds-page-organization-unit/src/app/app.component.html
  raaghu-mfe/projects/rds-page-organization-unit/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-organization-unit/src/app/organization-unit.stories.ts
  raaghu-mfe/projects/rds-page-product-details/src/app/app.component.html
  raaghu-mfe/projects/rds-page-product-details/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-product-details/src/app/product-details.stories.ts
  raaghu-mfe/projects/rds-page-settings/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-settings/src/app/settings.stories.ts
  raaghu-mfe/projects/rds-page-webhooksubscription/src/app/webhooksubscription.stories.ts
Labels: bug, storybook

#1462 UI changes in webhooksubscription
  raaghu-mfe/projects/rds-components/src/app/rds-comp-webhook-subscription/rds-comp-webhook-subscription.component.html
Labels: bug, ASP.net, Angular

#1463 Development abp Login Page
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.html
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/shared/src/lib/auth.guard.ts
  raaghu-mfe/projects/libs/shared/src/lib/user-auth.service.ts
  raaghu-mfe/projects/rds-components/src/app/app-routing.module.ts
  raaghu-mfe/projects/rds-components/src/app/app.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-alert/rds-comp-alert.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-features/rds-comp-features.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/login.md
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/rds-comp-tenant-list.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/rds-comp-user-permissions.component.html
  raaghu-mfe/projects/rds-components/webpack.config.js
  raaghu-mfe/projects/rds-page-dashboard/src/app/dashboard/dashboard.component.ts
  raaghu-mfe/projects/rds-page-login/src/app/app.component.html
  raaghu-mfe/projects/rds-page-login/src/app/app.component.scss
  raaghu-mfe/projects/rds-page-login/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-login/src/app/app.module.ts
Labels: ABP

#1464 Remember me checkbox functionality
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.ts
Labels: bug, Angular

#1465 Resolved storybook store front page issue
  raaghu-mfe/.storybook/assets/levelUp.png
  raaghu-mfe/projects/rds-page-store-front/src/app/app.component.html
  raaghu-mfe/projects/rds-page-store-front/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-store-front/src/app/store-front.stories.ts
Labels: bug, storybook, ASP.net

#1469 Storybook UI issues
  raaghu-elements/src/rds-search-input/src/lib/rds-search-input.component.scss
Labels: bug, ASP.net, Angular

#1474 Tooltip for the icons in the sidenav in Host admin
  raaghu-elements/src/rds-side-nav/src/lib/rds-side-nav.component.html
Labels: bug, ASP.net, Angular

#1479 commited for language translation
  raaghu-mfe/projects/host/src/assets/i18n/ar.json
  raaghu-mfe/projects/host/src/assets/i18n/fr.json
  raaghu-mfe/projects/host/src/assets/i18n/it.json
  raaghu-mfe/projects/host/src/assets/i18n/ru.json
  raaghu-mfe/projects/host/src/assets/i18n/th.json
  raaghu-mfe/projects/host/src/assets/i18n/tr.json
  raaghu-mfe/projects/host/src/assets/i18n/vi.json
Labels: bug, Angular, ABP

#1492 Kept only last 5 versions support in the browserlist
  raaghu-elements/package.json
  raaghu-mfe/package.json
Labels: bug, ASP.net, Angular

#1495 committed changes for data-table enhancement and dashboard alignment issue
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-data-table/rds-comp-data-table.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/models/table-header.model.ts
  raaghu-mfe/projects/rds-page-dashboard/src/app/dashboard/dashboard.component.html
  raaghu-mfe/projects/rds-page-dashboard/src/app/dashboard/dashboard.component.ts
Labels: bug, enhancement, ASP.net

#1508 Change the functionality of error handling.
  raaghu-elements/src/rds-input/src/lib/rds-input.component.html
  raaghu-elements/src/rds-input/src/lib/rds-input.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.html
Labels: enhancement, ASP.net, Angular

#1507 Resolved profile issue.
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.html
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/libs/shared/src/lib/app-session.service.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-notification/notification.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-notification/rds-comp-notification.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/profile.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/tenant.information.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-list/tenantlist.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-management/tenant-management.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-testimonials/rds-comp-testimonials.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basics/rds-comp-user-basics.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basics/rds-comp-user-basics.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basics/user-basics.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-management/rds-comp-user-management.module.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-management/user-management.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-permissions/user-permissions.stories.ts
  raaghu-mfe/projects/rds-page-cart/src/app/cart.stories.ts
  raaghu-mfe/projects/rds-page-tenant/src/app/tenant.stories.ts
Labels: bug, ASP.net, Angular

#1509 #1502 : Heading shows incorrect value
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-calendar/rds-comp-calendar.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-linked-accounts/rds-comp-linked-accounts.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.ts
  raaghu-mfe/projects/rds-page-dynamic-property-management/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-edition/src/app/app.component.ts
  raaghu-mfe/projects/rds-page-login/src/app/app.component.ts
Labels: bug, ASP.net, Angular

#1510 committed changes for raaghu text as bold and tenancy name size on dashboard
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
Labels: bug, ASP.net

#1512 Version changed for raaghu-themes
  raaghu-elements/package.json
  raaghu-mfe/package.json
  raaghu-mfe/projects/libs/shared/src/lib/app-session.service.ts
Labels: bug, ASP.net

#1514 Validations are added at button element's level
  raaghu-elements/src/rds-button/src/lib/rds-button.component.html
  raaghu-elements/src/rds-button/src/lib/rds-button.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.ts
Labels: bug, ASP.net, Angular

#1515 onClick validation has been changed.
  raaghu-elements/src/rds-button/src/lib/rds-button.component.html
  raaghu-elements/src/rds-button/src/lib/rds-button.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.ts
Labels: bug, ASP.net, Angular

#1516 #1504 : Text field shows double entries
  raaghu-mfe/projects/rds-page-edition/src/app/app.component.html
Labels: bug, ASP.net, Angular

#1521 fixed UI issues and iphones overlapping bugs
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.html
  raaghu-mfe/projects/host/src/app/sidenav/sidenav.component.scss
  raaghu-mfe/projects/host/src/index.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-login/rds-comp-login.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
Labels: bug

#1518 #1505 : After creating a new role the spinner is not went off
  raaghu-mfe/projects/rds-page-role/src/app/app.component.ts
Labels: bug, ASP.net, Angular

#1520 Create new icon comp.
  raaghu-mfe/projects/rds-components/src/app/rds-comp-icon/icon.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-icon/icons.json
  raaghu-mfe/projects/rds-components/src/app/rds-comp-icon/rds-comp-icon.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-icon/rds-comp-icon.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-icon/rds-comp-icon.module.ts
  raaghu-mfe/projects/rds-page-tenant/src/app/app.module.ts
Labels: Angular

#1522 Element and component updation for the error handling
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.html
  raaghu-elements/src/rds-dropdownlist/src/lib/rds-dropdownlist.component.ts
  raaghu-elements/src/rds-textarea/src/lib/rds-textarea.component.html
  raaghu-elements/src/rds-textarea/src/lib/rds-textarea.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-demoui/rds-comp-demoui.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-information/rds-comp-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-language/rds-comp-new-language.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-new-role/rds-comp-new-role.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-information/rds-comp-tenant-information.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-tenant-settings/rds-comp-tenant-settings.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-user-basics/rds-comp-user-basics.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-webhook-subscription/rds-comp-webhook-subscription.component.html
  raaghu-mfe/projects/rds-page-edition/src/app/app.component.html
Labels: enhancement, ASP.net, Angular

#1530 UI Changes in StageUI
  raaghu-mfe/projects/host/src/assets/i18n/aa-DJ.json
  raaghu-mfe/projects/host/src/assets/i18n/af-ZA.json
  raaghu-mfe/projects/host/src/assets/i18n/ar.json
  raaghu-mfe/projects/host/src/assets/i18n/de.json
  raaghu-mfe/projects/host/src/assets/i18n/en-GB.json
  raaghu-mfe/projects/host/src/assets/i18n/en.json
  raaghu-mfe/projects/host/src/assets/i18n/es-MX.json
  raaghu-mfe/projects/host/src/assets/i18n/es.json
  raaghu-mfe/projects/host/src/assets/i18n/fr.json
  raaghu-mfe/projects/host/src/assets/i18n/it.json
  raaghu-mfe/projects/host/src/assets/i18n/nl.json
  raaghu-mfe/projects/host/src/assets/i18n/pt-BR.json
  raaghu-mfe/projects/host/src/assets/i18n/ru.json
  raaghu-mfe/projects/host/src/assets/i18n/th.json
  raaghu-mfe/projects/host/src/assets/i18n/tr.json
  raaghu-mfe/projects/host/src/assets/i18n/vi.json
  raaghu-mfe/projects/host/src/assets/i18n/zh-Hans.json
  raaghu-mfe/projects/rds-components/src/app/rds-comp-admin-dashboard/rds-comp-admin-dashboard.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-profile/rds-comp-profile.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-top-navigation/rds-comp-top-navigation.component.html
  raaghu-mfe/projects/rds-page-audit-logs/src/app/app.component.html
  raaghu-mfe/projects/rds-page-tenant/src/app/app.component.html
Labels: bug, ASP.net, Angular

#1531 Adding icon comp into icon page
  raaghu-mfe/projects/rds-components/src/app/rds-comp-icon/icon.stories.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-icon/rds-comp-icon.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-icon/rds-comp-icon.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-icon/rds-comp-icon.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-icon/rds-comp-icon.module.ts
  raaghu-mfe/projects/rds-page-icon/src/app/app.component.html
  raaghu-mfe/projects/rds-page-icon/src/app/app.module.ts
Labels: enhancement, Angular

#1538 copy button functionality.
  raaghu-elements/src/rds-search-input/src/lib/rds-search-input.component.html
  raaghu-elements/src/rds-search-input/src/lib/rds-search-input.component.scss
  raaghu-mfe/package.json
  raaghu-mfe/projects/rds-components/src/app/rds-comp-icon/rds-comp-icon.component.html
  raaghu-mfe/projects/rds-components/src/app/rds-comp-icon/rds-comp-icon.component.scss
  raaghu-mfe/projects/rds-components/src/app/rds-comp-icon/rds-comp-icon.component.ts
  raaghu-mfe/projects/rds-components/src/app/rds-comp-icon/rds-comp-icon.module.ts
Labels: enhancement, storybook, ASP.net, Angular
